#!/usr/bin/env python3
"""monomial_lens.py -- automatic detection of latent quotient coordinates.

THE QUESTION.  Given a polynomial system f_1..f_m in declared variables V, do
some of the variables occur ONLY through a fixed monomial combination?  If they
do, naming that combination as a single new variable shrinks the system, and the
shrunk system's elimination ideals contract back EXACTLY (Lemma L below).  This
is the mechanism that collapsed GGHV22's "using a CAS (for example Mathematica)"
step at tex line 1689 (see GGHV_LINE1689.md): C_3 and F_-4 occur in the nine
printed equations only through E := F_-4 * C_3^23, after which the elimination is
a 3-equation / 2-unknown hand computation.

WHAT THIS MODULE DOES
  * builds the exponent matrix of the system over the declared variables;
  * LEVEL A (rank 1, COMPLETE): finds every maximal set S of variables whose
    exponent COLUMNS are pairwise proportional -- equivalently whose restricted
    exponent rows all lie on a single ray of the exponent lattice -- and emits
    z = prod_{v in S} v^{alpha_v}.  Because column proportionality is an
    equivalence relation, grouping columns by their primitive direction
    enumerates every maximal rank-1 merge and misses none;
  * LEVEL B (rank r >= 2): scans variable subsets for lattice degeneracy
    rank(M_S) = r < |S| and tries to realise it by r new coordinates;
  * LEVEL C: solves for the weight vectors making each input polynomial
    weighted-homogeneous (this is how the (72,108) u-weight grading is
    recovered mechanically rather than assumed);
  * for every proposal prints before/after statistics and an explicit
    SOUNDNESS OBLIGATION, and RUNS the machine-checkable parts of it;
  * REFUSES, with a named witness monomial, whenever a candidate variable also
    occurs outside the proposed combination.

SOUNDNESS.

  Let V be the declared variables, S a subset of V, alpha in Z_{>0}^S primitive.
  Write x^alpha = prod_{v in S} v^{alpha_v}, W = V \\ S, and let
      phi : A := Q[W][z]  -->  B := Q[V],   z |-> x^alpha,  phi|_{Q[W]} = id.

  (H1) EXCLUSIVITY.  For every monomial m of every f_i, the restriction of m's
       exponent vector to S equals k_m * alpha with k_m an integer >= 0.
  (H2) NONDEGENERACY.  alpha_v >= 1 for every v in S.

  Under (H1) each f_i has a unique preimage g_i in A, and:

  LEMMA L (contraction).  Assume (H1),(H2).  Put I = (f_1..f_m) in B and
  J = (g_1..g_m) in A.  Then for every subset U of W,   J cap Q[U] = I cap Q[U].

  Proof.  phi is injective on monomials (alpha != 0, and S and W are disjoint),
  so g_i is well defined and phi(J) is contained in I -- the "<=" direction,
  which is all a necessary-condition elimination needs.  For ">=": by (H2) every
  m in N^S factors uniquely as m = k*alpha + m' with k = min_v floor(m_v/alpha_v)
  and m' not >= alpha, so B is a FREE phi(A)-module on the basis
  {x^{m'} : m' in N^S, m' not >= alpha}, which contains 1.  Let pi : B -> phi(A)
  be the phi(A)-linear projection onto the basis element 1.  If h in I cap Q[U]
  then h = sum c_i f_i, and since h lies in phi(A)*1, h = pi(h) = sum pi(c_i) f_i
  lies in the phi(A)-ideal generated by the f_i, i.e. in phi(J).  phi is
  injective and h is in Q[U] which sits inside A, so h is in J cap Q[U].  QED

  So a LEVEL A merge is LOSSLESS for elimination into any subset of the surviving
  variables: nothing is added and nothing is lost.  For LEVEL B (r >= 2 new
  coordinates) only "<=" is claimed here -- freeness of B over phi(A) can fail
  for a rank-r monoid -- so the converse is printed as an UNDISCHARGED
  obligation rather than asserted.

  If (H1) fails the substitution is UNSOUND; the tool refuses and names the
  offending polynomial and monomial.

REGRESSION SUITE (`--quiet` exits 0 iff all behave as recorded):
  1  GGHV22 tex-1689, the nine printed equations -> must rediscover E = F_-4*C_3^23
  1b control: the same with the three equations the paper drops -> must REFUSE
  2  the seven G5body terms -> must recover d0=4,d1=3,d2=2,dm1=5,dm2=6,dm3=7,
     dm4=8 with common u-weight 17, from the monomials alone
  3  a deliberate negative control -> must REFUSE (plus a positive control)
  4  the R9 z=1 dm4-eliminated H-system -> reports whatever it finds

Read-only on every existing artifact.  Exact arithmetic throughout; the only
randomness is an extra exact-rational spot check of the lift.
"""
from __future__ import annotations

import argparse
import itertools
import json
import os
import random
import sys
from fractions import Fraction
from math import gcd

import sympy as sp

HERE = os.path.dirname(os.path.abspath(__file__)) or "."


# =====================================================================
#  0.  exponent data
# =====================================================================
class ExpData:
    """Exponent matrix of a system over a declared variable list.

    Symbols NOT in `variables` are treated as coefficients (they live in the
    coefficient domain of the sympy Poly) and are invisible to the lens.
    """

    def __init__(self, polys, variables, labels=None):
        self.vars = [sp.sympify(v) for v in variables]
        self.n = len(self.vars)
        self.polys = [sp.expand(sp.sympify(p)) for p in polys]
        self.labels = list(labels) if labels else ["f%d" % i for i in range(len(self.polys))]
        self.mons = []            # deduplicated global list of exponent tuples
        self.per_poly = []
        self.coeffs = []
        seen = {}
        pos = {v: i for i, v in enumerate(self.vars)}
        for f in self.polys:
            if f == 0:
                self.per_poly.append([])
                self.coeffs.append([])
                continue
            ms, cs = self._split(f, pos)
            self.per_poly.append(ms)
            self.coeffs.append(cs)
            for m in ms:
                if m not in seen:
                    seen[m] = len(self.mons)
                    self.mons.append(m)
        self.index = seen
        self._cols = None

    @staticmethod
    def _split(f, pos):
        """Split an EXPANDED polynomial into (exponent tuples, coefficient parts)
        over the declared variables, walking the expression tree directly.

        sp.Poly(f, *vars) is equivalent but builds a multivariate domain over all
        declared generators, which is prohibitive at 30+ variables and 10^5 terms;
        this walk is linear in the number of terms.  Fail-loud on any non
        nonnegative-integer exponent of a declared variable.
        """
        n = len(pos)
        ms, cs = [], []
        for term in sp.Add.make_args(f):
            exps = [0] * n
            coeff = sp.Integer(1)
            for fac in sp.Mul.make_args(term):
                base, e = fac.as_base_exp()
                j = pos.get(base)
                if j is None:
                    coeff *= fac
                    continue
                if not (e.is_Integer and e >= 0):
                    raise ValueError(
                        "declared variable %s occurs with exponent %s (not a "
                        "nonnegative integer); the lens needs a polynomial input"
                        % (base, e))
                exps[j] += int(e)
            ms.append(tuple(exps))
            cs.append(coeff)
        return ms, cs

    def column(self, j):
        if self._cols is None:
            self._cols = [tuple(m[j] for m in self.mons) for j in range(self.n)]
        return self._cols[j]

    def occurring(self):
        return [j for j in range(self.n) if any(self.column(j))]

    def mon_str(self, m):
        parts = []
        for j, e in enumerate(m):
            if e == 1:
                parts.append(str(self.vars[j]))
            elif e:
                parts.append("%s^%d" % (self.vars[j], e))
        return "*".join(parts) if parts else "1"

    def which_poly(self, mon):
        for lab, ms in zip(self.labels, self.per_poly):
            if mon in ms:
                return lab
        return "?"

    def single_site_vars(self):
        """Variables occurring in exactly one distinct monomial of the system."""
        out = []
        for j in range(self.n):
            col = self.column(j)
            nz = [i for i, e in enumerate(col) if e]
            if len(nz) == 1:
                out.append((str(self.vars[j]), self.mon_str(self.mons[nz[0]])))
        return out

    def stats(self):
        present = self.occurring()
        edges = set()
        for m in self.mons:
            sup = [j for j in range(self.n) if m[j]]
            for a, b in itertools.combinations(sorted(sup), 2):
                edges.add((a, b))
        parent = {j: j for j in present}

        def find(x):
            while parent[x] != x:
                parent[x] = parent[parent[x]]
                x = parent[x]
            return x

        for a, b in edges:
            ra, rb = find(a), find(b)
            if ra != rb:
                parent[ra] = rb
        comps = len({find(j) for j in present}) if present else 0
        deg = {j: 0 for j in present}
        for a, b in edges:
            deg[a] += 1
            deg[b] += 1
        return {
            "n_declared_vars": self.n,
            "n_occurring_vars": len(present),
            "n_distinct_monomials": len(self.mons),
            "max_total_degree": max((sum(m) for m in self.mons), default=0),
            "graph_edges": len(edges),
            "graph_components": comps,
            "graph_max_degree": max(deg.values()) if deg else 0,
        }


# =====================================================================
#  1.  LEVEL A -- rank-1 (ray) merges, via column proportionality
# =====================================================================
def _primitive(vec):
    """(g, u) with vec = g*u and u a primitive integer vector; (0, None) if 0."""
    g = 0
    for e in vec:
        g = gcd(g, abs(int(e)))
    if g == 0:
        return 0, None
    return g, tuple(int(e) // g for e in vec)


def ray_merge_classes(ed: ExpData):
    """ALL maximal rank-1 merges (complete, see module docstring)."""
    buckets = {}
    for j in range(ed.n):
        g, u = _primitive(ed.column(j))
        if u is None:
            continue                        # variable does not occur at all
        buckets.setdefault(u, []).append((j, g))
    out = []
    for u, members in buckets.items():
        if len(members) < 2:
            continue
        gs = [g for _, g in members]
        G = 0
        for g in gs:
            G = gcd(G, g)
        alpha = [g // G for g in gs]
        idx = [j for j, _ in members]
        out.append({
            "vars": [str(ed.vars[j]) for j in idx],
            "var_idx": idx,
            "alpha": alpha,
            "rank": 1,
        })
    out.sort(key=lambda d: -len(d["vars"]))
    return out


def merge_expr(ed: ExpData, var_idx, alpha):
    e = sp.Integer(1)
    for j, a in zip(var_idx, alpha):
        e *= ed.vars[j] ** a
    return e


# =====================================================================
#  2.  soundness: (H1), (H2), the lift, the checks, the obligation text
# =====================================================================
def check_exclusivity(ed: ExpData, var_idx, alpha):
    """(H1).  Returns (ok, k_per_global_monomial, violations)."""
    viol = []
    ks = []
    for m in ed.mons:
        restricted = [m[j] for j in var_idx]
        if all(e == 0 for e in restricted):
            ks.append(0)
            continue
        k, bad = None, False
        for e, a in zip(restricted, alpha):
            if a == 0:
                if e != 0:
                    bad = True
                    break
                continue
            if e % a != 0:
                bad = True
                break
            kk = e // a
            if k is None:
                k = kk
            elif k != kk:
                bad = True
                break
        if bad or k is None or k < 0:
            viol.append({
                "poly": ed.which_poly(m),
                "monomial": ed.mon_str(m),
                "restriction": {str(ed.vars[j]): m[j] for j in var_idx},
                "reason": "S-restriction is not a nonnegative integer multiple of alpha",
            })
            ks.append(None)
        else:
            ks.append(k)
    return (not viol), ks, viol


def apply_merge(ed: ExpData, var_idx, alpha, zname="z"):
    """Rewrite in quotient coordinates.  Returns (new_polys, new_vars, z, lift_ok).
    Raises if (H1) fails -- the tool never silently applies an unsound merge."""
    ok, ks, viol = check_exclusivity(ed, var_idx, alpha)
    if not ok:
        raise ValueError("UNSOUND merge refused: %r" % (viol[:2],))
    S = set(var_idx)
    z = sp.Symbol(zname)
    keep = [j for j in range(ed.n) if j not in S]
    new_vars = [ed.vars[j] for j in keep] + [z]
    new_polys = []
    for ms, cs in zip(ed.per_poly, ed.coeffs):
        acc = sp.Integer(0)
        for m, c in zip(ms, cs):
            k = ks[ed.index[m]]
            term = sp.sympify(c)
            for j in keep:
                if m[j]:
                    term *= ed.vars[j] ** m[j]
            if k:
                term *= z ** k
            acc += term
        new_polys.append(sp.expand(acc))
    phi = {z: merge_expr(ed, var_idx, alpha)}
    lift_ok = all(sp.expand(g.xreplace(phi) - f) == 0
                  for g, f in zip(new_polys, ed.polys))
    return new_polys, new_vars, z, lift_ok


def numeric_lift_check(ed: ExpData, new_polys, var_idx, alpha, z, trials=5, seed=11):
    """Exact-rational spot check: sample x, set z = x^alpha, compare g and f."""
    rng = random.Random(seed)
    S = set(var_idx)
    params = set()
    for f in ed.polys:
        params |= f.free_symbols
    params -= set(ed.vars)
    for _ in range(trials):
        pt = {v: sp.Rational(rng.randint(1, 9), rng.randint(1, 5)) for v in ed.vars}
        pt.update({s: sp.Rational(rng.randint(1, 9), rng.randint(1, 5)) for s in params})
        zval = sp.Integer(1)
        for j, a in zip(var_idx, alpha):
            zval *= pt[ed.vars[j]] ** a
        down = {ed.vars[j]: pt[ed.vars[j]] for j in range(ed.n) if j not in S}
        down.update({s: pt[s] for s in params})
        down[z] = zval
        for g, f in zip(new_polys, ed.polys):
            if sp.nsimplify(g.xreplace(down) - f.xreplace(pt)) != 0:
                return False
    return True


def obligation_text(ed, var_idx, alpha, zname, exclusivity_ok, n_mon_checked,
                    lift_ok, numeric_ok, rank=1):
    S = [str(ed.vars[j]) for j in var_idx]
    zdef = "*".join("%s^%d" % (s, a) if a != 1 else s for s, a in zip(S, alpha))
    L = ["SOUNDNESS OBLIGATION for  %s := %s" % (zname, zdef),
         "  (H1) EXCLUSIVITY -- every monomial of every input polynomial restricts",
         "       on {%s} to a nonnegative integer multiple of alpha = %s."
         % (", ".join(S), tuple(alpha)),
         "       CHECKED on %d distinct monomials: %s"
         % (n_mon_checked, "PASS" if exclusivity_ok else "*** FAIL -- REFUSED ***"),
         "  (H2) NONDEGENERACY -- alpha_v >= 1 for every merged v:  %s"
         % ("PASS" if all(a >= 1 for a in alpha) else "*** FAIL ***"),
         "  (L1) LIFT EXACTNESS -- phi(g_i) - f_i == 0 identically, all i:  %s"
         % ("PASS" if lift_ok else "*** FAIL ***"),
         "  (L2) NUMERIC CROSS-CHECK -- random exact-rational points:  %s"
         % ("PASS" if numeric_ok else "*** FAIL ***")]
    if rank == 1:
        L += ["  ==> LEMMA L applies: for every subset U of the surviving variables,",
              "      J cap Q[U] = I cap Q[U].  LOSSLESS in both directions."]
    else:
        L += ["  ==> rank-%d merge: only J cap Q[U] <= I cap Q[U] is claimed." % rank,
              "      UNDISCHARGED: the converse needs B free over phi(A), which can",
              "      FAIL for a rank->=2 monoid.  Verify separately."]
    return "\n".join(L)


# =====================================================================
#  3.  LEVEL B -- higher-rank lattice degeneracy on variable subsets
# =====================================================================
def _rank_frac(rows):
    M = [[Fraction(int(x)) for x in r] for r in rows]
    nr, nc = len(M), (len(M[0]) if M else 0)
    rank = 0
    for c in range(nc):
        piv = None
        for i in range(rank, nr):
            if M[i][c] != 0:
                piv = i
                break
        if piv is None:
            continue
        M[rank], M[piv] = M[piv], M[rank]
        pv = M[rank][c]
        M[rank] = [x / pv for x in M[rank]]
        for i in range(nr):
            if i != rank and M[i][c] != 0:
                f = M[i][c]
                M[i] = [a - f * b for a, b in zip(M[i], M[rank])]
        rank += 1
        if rank == nr:
            break
    return rank


def _nonneg_int_combo(target, gens):
    """Exact solve target = sum k_i gens_i; return the integer nonneg k or None."""
    ncol = len(gens)
    A = sp.Matrix([[sp.Integer(g[j]) for g in gens] for j in range(len(target))])
    b = sp.Matrix([sp.Integer(t) for t in target])
    aug = A.row_join(b)
    if A.rank() != aug.rank():
        return None
    x = A.solve_least_squares(b)
    if sp.simplify(A * x - b) != sp.zeros(A.rows, 1):
        return None
    out = []
    for v in x:
        v = sp.Rational(sp.nsimplify(v))
        if v < 0 or v.q != 1:
            return None
        out.append(int(v))
    return out if len(out) == ncol else None


def _independent_rows(rows, ncols):
    """Exact greedy elimination: return original rows forming a basis of the row
    space (at most ncols of them).  Stops as soon as full rank is reached."""
    red, piv, orig = [], [], []
    for row in rows:
        v = [Fraction(int(x)) for x in row]
        for b, pc in zip(red, piv):
            if v[pc] != 0:
                f = v[pc]
                v = [a - f * c for a, c in zip(v, b)]
        nz = next((i for i, x in enumerate(v) if x != 0), None)
        if nz is None:
            continue
        inv = v[nz]
        v = [x / inv for x in v]
        red.append(v)
        piv.append(nz)
        orig.append(row)
        if len(red) == ncols:
            break
    return orig


def exponent_lattice(ed: ExpData):
    """Rank of the Z-span of the exponent rows, restricted to occurring variables.

    torus_dim = (#occurring vars) - rank is the dimension of the space of weight
    vectors under which EVERY monomial has weight 0.  torus_dim = 0 is the
    strongest possible negative result: the system admits no monomial change of
    coordinates that loses a variable, not even a Laurent one."""
    present = ed.occurring()
    rows = sorted({tuple(m[j] for j in present) for m in ed.mons})
    rows = [r for r in rows if any(r)]
    ind = _independent_rows(rows, len(present))
    r = len(ind)
    gens = []
    if rows and len(present) - r > 0:
        M = sp.Matrix([[sp.Integer(x) for x in row] for row in ind])
        for v in M.nullspace():
            rats = [sp.Rational(sp.nsimplify(x)) for x in v]
            den = sp.ilcm(*[q.q for q in rats])
            ints = [int(q * den) for q in rats]
            g = 0
            for x in ints:
                g = gcd(g, abs(x))
            if g:
                ints = [x // g for x in ints]
            gens.append({str(ed.vars[j]): e for j, e in zip(present, ints) if e})
    return {"n_occurring": len(present), "lattice_rank": r,
            "torus_dim": len(present) - r, "null_gradings": gens}


def _low_support_relations(null_basis, bound=3, max_report=12):
    """Minimal-support nonzero integer vectors in the lattice spanned by
    `null_basis` (a list of integer tuples).  Small integer combinations are
    enumerated; for dimension 1 this is exact, for higher dimension it is a
    bounded search and is reported as such."""
    d = len(null_basis)
    if d == 0:
        return []
    n = len(null_basis[0])
    seen = {}
    rng = range(-bound, bound + 1)
    for coeffs in itertools.product(rng, repeat=d):
        if all(c == 0 for c in coeffs):
            continue
        v = [sum(c * b[j] for c, b in zip(coeffs, null_basis)) for j in range(n)]
        if not any(v):
            continue
        g = 0
        for x in v:
            g = gcd(g, abs(x))
        v = tuple(x // g for x in v)
        if v[next(i for i, x in enumerate(v) if x)] < 0:
            v = tuple(-x for x in v)
        sup = frozenset(i for i, x in enumerate(v) if x)
        if sup not in seen:
            seen[sup] = v
    best = sorted(seen.items(), key=lambda kv: len(kv[0]))
    return [(sorted(s), v) for s, v in best[:max_report]]


def lattice_merges(ed: ExpData, max_subset=6, max_rows_for_gens=20, level_a=None,
                   ed_lattice=None):
    """LEVEL B -- degenerate variable subsets, found via LOW-SUPPORT LATTICE
    RELATIONS instead of a blind subset scan.

    KEY FACT (this is what makes the search both complete and cheap): if a
    subset S has rank(M_S) < |S| then some nonzero weight vector w supported
    inside S satisfies M_S w_S = 0; extending w by zero gives M w = 0.  So EVERY
    degenerate subset contains the support of a nonzero vector of the global
    exponent-matrix null space.  In particular:

        torus_dim = 0  ==>  NO subset of ANY size is degenerate.

    The scan therefore reduces to: compute the null space, extract its minimal
    supports, and test those (and nothing else).  Results whose whole rank drop
    is already explained by a LEVEL A class are flagged `subsumed`.
    """
    present = ed.occurring()
    el = ed_lattice if ed_lattice is not None else exponent_lattice(ed)
    if el["torus_dim"] == 0:
        return []                       # PROVED empty -- no scan needed
    rows = sorted({tuple(m[j] for j in present) for m in ed.mons})
    rows = [r for r in rows if any(r)]
    ind = _independent_rows(rows, len(present))
    M = sp.Matrix([[sp.Integer(x) for x in r] for r in ind])
    basis = []
    for v in M.nullspace():
        rats = [sp.Rational(sp.nsimplify(x)) for x in v]
        den = sp.ilcm(*[q.q for q in rats])
        basis.append(tuple(int(q * den) for q in rats))
    a_classes = [set(c["var_idx"]) for c in (level_a or [])]
    found = []
    for sup_local, vec in _low_support_relations(basis):
        S = [present[i] for i in sup_local]
        if len(S) < 2 or len(S) > max_subset:
            continue
        srows = sorted({tuple(m[j] for j in S) for m in ed.mons})
        srows = [r for r in srows if any(r)]
        if len(srows) < 2:
            continue
        r = _rank_frac(srows)
        if r >= len(S):
            continue
        gens_ok = None
        for gens in itertools.combinations(srows[:max_rows_for_gens], r):
            if _rank_frac(list(gens)) < r:
                continue
            if all(_nonneg_int_combo(row, list(gens)) is not None for row in srows):
                gens_ok = gens
                break
        names = [str(ed.vars[j]) for j in S]
        explained = sum(max(0, len(c & set(S)) - 1) for c in a_classes)
        found.append({
            "vars": names,
            "var_idx": list(S),
            "rank": r,
            "relation": {names[i]: vec[j] for i, j in enumerate(sup_local)},
            "subsumed": (len(S) - r) <= explained,
            "realisable": gens_ok is not None,
            "generators": ["*".join("%s^%d" % (names[i], e) if e != 1 else names[i]
                                    for i, e in enumerate(g) if e)
                           for g in gens_ok] if gens_ok else None,
        })
    return found


# =====================================================================
#  4.  LEVEL C -- weighted-homogeneity gradings
# =====================================================================
def grading_space(ed: ExpData):
    """Solve for w in Q^n and per-polynomial constants c_f with
    <exponent(m), w> = c_f for every monomial m of f.  Coordinates of the
    returned nullspace vectors are (w_1..w_n, c_1..c_m)."""
    nvar, npol = ed.n, len(ed.polys)
    rows = []
    for pi, ms in enumerate(ed.per_poly):
        for m in ms:
            row = [sp.Integer(e) for e in m] + [sp.Integer(0)] * npol
            row[nvar + pi] = sp.Integer(-1)
            rows.append(row)
    if not rows:
        return {"dim": nvar + npol, "basis": [], "n_constraints": 0}
    M = sp.Matrix(rows)
    ns = M.nullspace()
    return {"dim": len(ns), "basis": [list(v) for v in ns], "n_constraints": M.rows,
            "vars": [str(v) for v in ed.vars], "polys": list(ed.labels)}


def grading_contains(gs, weights, consts):
    """Exact test: is (w, c) in the span of the grading-space basis?"""
    if not gs["basis"]:
        return all(sp.Rational(x) == 0 for x in list(weights) + list(consts))
    B = sp.Matrix.hstack(*[sp.Matrix(v) for v in gs["basis"]])
    tgt = sp.Matrix([sp.Rational(x) for x in list(weights) + list(consts)])
    return B.rank() == B.row_join(tgt).rank()


def primitive_generator(gs, names):
    """If the grading space is 1-dimensional, return its primitive integer
    generator as a dict {name: weight}; else None."""
    if gs["dim"] != 1:
        return None
    rats = [sp.Rational(sp.nsimplify(x)) for x in gs["basis"][0]]
    den = sp.ilcm(*[r.q for r in rats]) if rats else 1
    ints = [int(r * den) for r in rats]
    g = 0
    for x in ints:
        g = gcd(g, abs(x))
    if g:
        ints = [x // g for x in ints]
    if ints and ints[0] < 0:
        ints = [-x for x in ints]
    return dict(zip(names, ints))


# =====================================================================
#  5.  top-level driver
# =====================================================================
def blocked_pairs(ed: ExpData, limit=10):
    """For pairs of occurring variables whose columns are NOT proportional,
    record a witness monomial.  This is the 'why not' diagnosis that makes a
    refusal informative rather than a bare no."""
    present = ed.occurring()
    out = []
    for a, b in itertools.combinations(present, 2):
        ca, cb = ed.column(a), ed.column(b)
        _, ua = _primitive(ca)
        _, ub = _primitive(cb)
        if ua == ub:
            continue
        wit = None
        for i, m in enumerate(ed.mons):
            if (ca[i] == 0) != (cb[i] == 0):
                wit = m
                break
        if wit is None:
            for i, m in enumerate(ed.mons):
                if ua[i] != ub[i]:
                    wit = m
                    break
        if wit is not None:
            out.append({"pair": (str(ed.vars[a]), str(ed.vars[b])),
                        "witness_monomial": ed.mon_str(wit),
                        "witness_poly": ed.which_poly(wit)})
        if len(out) >= limit:
            break
    return out


def lens(polys, variables, labels=None, name="system", max_subset=4,
         verbose=True, do_lattice=True, zname="z"):
    ed = ExpData(polys, variables, labels)
    before = ed.stats()
    result = {"name": name, "before": before, "proposals": [], "refusals": [],
              "single_site": ed.single_site_vars()}

    cands = ray_merge_classes(ed)
    for ci, cand in enumerate(cands):
        ok, ks, viol = check_exclusivity(ed, cand["var_idx"], cand["alpha"])
        zn = zname if len(cands) == 1 else "%s%d" % (zname, ci + 1)
        if not ok:
            result["refusals"].append({"vars": cand["vars"], "violations": viol[:4]})
            continue
        new_polys, new_vars, z, lift_ok = apply_merge(ed, cand["var_idx"],
                                                      cand["alpha"], zn)
        num_ok = numeric_lift_check(ed, new_polys, cand["var_idx"], cand["alpha"], z)
        after = ExpData(new_polys, new_vars, ed.labels).stats()
        result["proposals"].append({
            "rank": 1, "vars": cand["vars"], "alpha": cand["alpha"], "z": zn,
            "z_def": str(merge_expr(ed, cand["var_idx"], cand["alpha"])),
            "before": before, "after": after,
            "gain": {k: before[k] - after[k] for k in before},
            "exclusivity": ok, "lift_ok": lift_ok, "numeric_ok": num_ok,
            "obligation": obligation_text(ed, cand["var_idx"], cand["alpha"], zn,
                                          ok, len(ed.mons), lift_ok, num_ok, 1),
            "new_polys": new_polys, "new_vars": new_vars,
        })

    result["blocked"] = blocked_pairs(ed)
    el = exponent_lattice(ed)
    result["exponent_lattice"] = el
    result["lattice"] = (lattice_merges(ed, max_subset=max_subset, level_a=cands,
                                       ed_lattice=el) if do_lattice else [])
    if verbose:
        print_report(ed, result)
    result["_ed"] = ed
    return result


def print_report(ed: ExpData, res):
    b = res["before"]
    print("=" * 78)
    print("MONOMIAL LENS  --  %s" % res["name"])
    print("-" * 78)
    print("  declared vars %d (occurring %d) | distinct monomials %d | max total deg %d"
          % (b["n_declared_vars"], b["n_occurring_vars"], b["n_distinct_monomials"],
             b["max_total_degree"]))
    print("  interaction graph: %d edges, %d components, max degree %d"
          % (b["graph_edges"], b["graph_components"], b["graph_max_degree"]))
    if res["single_site"]:
        print("  single-site variables (occur in exactly one distinct monomial):")
        for v, m in res["single_site"][:10]:
            print("     %-10s only in  %s" % (v, m))
    if not res["proposals"] and not res["refusals"]:
        print("  LEVEL A (rank-1 merges): NONE.  No set of declared variables occurs")
        print("     only through a fixed monomial combination.")
    for p in res["proposals"]:
        a = p["after"]
        print("  *** LEVEL A MERGE PROPOSAL:  %s := %s" % (p["z"], p["z_def"]))
        print("      merges %s   alpha = %s" % (", ".join(p["vars"]), tuple(p["alpha"])))
        print("      occurring vars   %3d -> %3d" % (b["n_occurring_vars"], a["n_occurring_vars"]))
        print("      distinct monoms  %3d -> %3d" % (b["n_distinct_monomials"], a["n_distinct_monomials"]))
        print("      max total degree %3d -> %3d" % (b["max_total_degree"], a["max_total_degree"]))
        print("      graph edges      %3d -> %3d" % (b["graph_edges"], a["graph_edges"]))
        for line in p["obligation"].splitlines():
            print("      " + line)
    for r in res["refusals"]:
        print("  *** REFUSED merge of %s -- (H1) exclusivity fails:" % ", ".join(r["vars"]))
        for v in r["violations"]:
            print("        %s: monomial %s  (%s)" % (v["poly"], v["monomial"], v["reason"]))
    el = res.get("exponent_lattice")
    if el:
        print("  exponent lattice: rank %d over %d occurring variables"
              % (el["lattice_rank"], el["n_occurring"]))
        if el["torus_dim"] == 0:
            print("     torus dimension 0 -- NO weight vector makes every monomial")
            print("     weight 0, so no monomial coordinate change of ANY kind (not even")
            print("     Laurent) can lose a variable.  Strongest form of a negative.")
        else:
            print("     torus dimension %d -- a %d-parameter family of monomial"
                  % (el["torus_dim"], el["torus_dim"]))
            print("     symmetries exists, so AT MOST %d variable%s can ever be lost."
                  % (el["torus_dim"], "" if el["torus_dim"] == 1 else "s"))
            for g in el.get("null_gradings", [])[:3]:
                print("        null grading: %s" % g)
    lat = [d for d in res.get("lattice", []) if d["rank"] >= 2 and not d.get("subsumed")]
    sub = [d for d in res.get("lattice", []) if d.get("subsumed")]
    if lat:
        print("  LEVEL B (rank r < |S|) NEW degeneracies: %d  (+%d subsumed by LEVEL A)"
              % (len(lat), len(sub)))
        for d in lat[:8]:
            print("     S=%s rank=%d realisable=%s gens=%s"
                  % (d["vars"], d["rank"], d["realisable"], d["generators"]))
    else:
        print("  LEVEL B (rank r < |S|): no NEW degeneracies in the scanned subsets"
              " (%d subsumed by LEVEL A)." % len(sub))
    if res.get("blocked"):
        print("  blocked pairs (why no merge) -- witness monomials:")
        for d in res["blocked"][:6]:
            print("     %-18s blocked by %s in %s"
                  % ("%s / %s" % d["pair"], d["witness_monomial"], d["witness_poly"]))
    print()


# =====================================================================
#  6.  REG1 -- GGHV22 tex line 1689
# =====================================================================
def _gghv_series(N=14):
    """Regenerate (D~^2)_{-k}, (D~^3)_{-k}, (D~^{-1})_{-k} from the series
    definition of D~ = x^3 + x d_1 + d_0 + x^{-1}d_{-1} + ... (d_3=1, d_2=0),
    the same construction as the scratchpad gen_eqs.py.  Used both to build the
    equations the paper OMITS and to re-verify the nine printed ones."""
    t = sp.Symbol("t")
    d = {3: sp.Integer(1), 2: sp.Integer(0), 1: sp.Symbol("d1"), 0: sp.Symbol("d0")}
    for k in range(1, N + 1):
        d[-k] = sp.Symbol("dm%d" % k)
    TRUNC = N + 6
    A = sum(d[k] * t ** (3 - k) for k in sorted(d, reverse=True))

    def trunc(expr):
        p = sp.expand(expr)
        return sum(p.coeff(t, i) * t ** i for i in range(TRUNC + 1))

    A2 = trunc(sp.expand(A ** 2))
    A3 = trunc(sp.expand(A ** 3))
    Ainv = sp.Integer(1)
    rest = trunc(A - 1)
    term = sp.Integer(1)
    for _ in range(1, TRUNC + 1):
        term = trunc(term * (-rest))
        Ainv = Ainv + term
    Ainv = trunc(Ainv)
    D2 = lambda k: sp.expand(sp.expand(A2).coeff(t, k + 6))          # noqa: E731
    D3 = lambda k: sp.expand(sp.expand(A3).coeff(t, k + 9))          # noqa: E731
    Dinv = lambda k: (sp.Integer(0) if k - 3 < 0                     # noqa: E731
                      else sp.expand(sp.expand(Ainv).coeff(t, k - 3)))
    return D2, D3, Dinv, d


def gghv_1689_system(include_omitted=False, verify_transcription=True):
    """The NINE printed equations of GGHV22 (arXiv:2204.14178) tex lines
    1675-1687, with C_3, F_-4 and lambda LEFT UNLUMPED.

    The transcription is checked against an independent regeneration from the
    series definitions (fail-loud); the LaTeX typo "2 d_{-1}0" at tex 1680 is
    read as "2 d_{-10}" (see GGHV_LINE1689.md sec.5).

    include_omitted=True adds the three equations the paper explicitly does NOT
    use -- (D~^2)_{-6}, (D~^2)_{-8} and (Q~)_{-3}, the last being the unique one
    carrying lambda*C_3^20.  That is the control showing the lens's refusal is
    sensitive: with (Q~)_{-3} present, C_3 no longer occurs only through
    F_-4*C_3^23 and the merge must be REFUSED.
    """
    d1, d0 = sp.symbols("d1 d0")
    dm = {k: sp.Symbol("dm%d" % k) for k in range(1, 12)}
    C3, Fm4, lam = sp.symbols("C3 Fm4 lam")
    dm1, dm2, dm3, dm4, dm5 = dm[1], dm[2], dm[3], dm[4], dm[5]
    dm6, dm7, dm8, dm9, dm10, dm11 = dm[6], dm[7], dm[8], dm[9], dm[10], dm[11]

    printed = [
        ("D2_-1", 2*d0*dm1 + 2*d1*dm2 + 2*dm4),
        ("D2_-2", dm1**2 + 2*d0*dm2 + 2*d1*dm3 + 2*dm5),
        ("D2_-3", 2*dm1*dm2 + 2*d0*dm3 + 2*d1*dm4 + 2*dm6),
        ("D2_-4", dm2**2 + 2*dm1*dm3 + 2*d0*dm4 + 2*d1*dm5 + 2*dm7),
        ("D2_-5", 2*dm2*dm3 + 2*dm1*dm4 + 2*d0*dm5 + 2*d1*dm6 + 2*dm8),
        ("D2_-7", 2*dm10 + 2*dm3*dm4 + 2*dm2*dm5 + 2*dm1*dm6 + 2*d0*dm7 + 2*d1*dm8),
        ("Q_-1", 3*d0**2*dm1 + 3*d1*dm1**2 + 6*d0*d1*dm2 + 3*dm2**2 + 3*d1**2*dm3
                 + 6*dm1*dm3 + 6*d0*dm4 + 6*d1*dm5 + 3*dm7),
        ("Q_-2", 3*d0*dm1**2 + 3*d0**2*dm2 + 6*d1*dm1*dm2 + 6*d0*d1*dm3 + 6*dm2*dm3
                 + 3*d1**2*dm4 + 6*dm1*dm4 + 6*d0*dm5 + 6*d1*dm6 + 3*dm8),
        ("Q_-4", 3*dm10 + 3*dm1**2*dm2 + 3*d0*dm2**2 + 6*d0*dm1*dm3 + 6*d1*dm2*dm3
                 + 3*d0**2*dm4 + 6*d1*dm1*dm4 + 6*dm3*dm4 + 6*d0*d1*dm5 + 6*dm2*dm5
                 + 3*d1**2*dm6 + 6*dm1*dm6 + 6*d0*dm7 + 6*d1*dm8
                 + Fm4 * C3**23),
    ]
    D2, D3, Dinv, _d = _gghv_series()
    lam_full = lam * C3**20

    def Qk(k):
        return sp.expand(D3(k) + lam_full * Dinv(k)
                         + (Fm4 * C3**23 if k == 4 else 0))

    if verify_transcription:
        gen = {"D2_-1": D2(1), "D2_-2": D2(2), "D2_-3": D2(3), "D2_-4": D2(4),
               "D2_-5": D2(5), "D2_-7": D2(7),
               "Q_-1": Qk(1), "Q_-2": Qk(2), "Q_-4": Qk(4)}
        for name, expr in printed:
            diff = sp.expand(gen[name] - expr)
            if diff != 0:
                raise AssertionError(
                    "GGHV transcription check FAILED for %s: generated - printed = %s"
                    % (name, diff))

    eqs = list(printed)
    variables = [d1, d0, dm1, dm2, dm3, dm4, dm5, dm6, dm7, dm8, dm10, C3, Fm4]
    if include_omitted:
        eqs += [("D2_-6", D2(6)), ("D2_-8", D2(8)), ("Q_-3", Qk(3))]
        variables = variables + [dm9, dm11, lam]
    labels = [k for k, _ in eqs]
    polys = [v for _, v in eqs]
    target = 18*C3**23*d1*dm1**6*Fm4 + 8*C3**69*Fm4**3 + 27*d0*dm1**9
    return polys, variables, labels, target, (C3, Fm4)


def regression_1(verbose=True):
    polys, variables, labels, target, (C3, Fm4) = gghv_1689_system()
    res = lens(polys, variables, labels,
               name="REG1  GGHV22 tex-1689, the nine printed equations",
               verbose=verbose, max_subset=3, zname="E")
    ed = res["_ed"]
    hit = None
    for p in res["proposals"]:
        if set(p["vars"]) == {"C3", "Fm4"}:
            hit = p
    ok = hit is not None
    detail = {}
    if ok:
        a = dict(zip(hit["vars"], hit["alpha"]))
        ok = (a["C3"] == 23 and a["Fm4"] == 1 and hit["lift_ok"] and hit["numeric_ok"])
        detail["z_def"] = hit["z_def"]
        detail["gain"] = {k: hit["gain"][k] for k in
                          ("n_occurring_vars", "n_distinct_monomials", "max_total_degree")}
        # the paper's printed answer must transform to 8E^3 + 18E d1 dm1^6 + 27 d0 dm1^9
        ed_t = ExpData([target], variables, ["ecuacion principal"])
        idx = [variables.index(C3), variables.index(Fm4)]
        exc, ks, viol = check_exclusivity(ed_t, idx, [23, 1])
        detail["target_exclusivity"] = exc
        if exc:
            tp, tv, z, lift = apply_merge(ed_t, idx, [23, 1], "E")
            detail["target_in_E"] = str(sp.expand(tp[0]))
            d1, d0, dm1 = sp.symbols("d1 d0 dm1")
            expect = 18*z*d1*dm1**6 + 8*z**3 + 27*d0*dm1**9
            detail["matches_GGHV_LINE1689_sec3"] = bool(sp.expand(tp[0] - expect) == 0)
            ok = ok and lift and detail["matches_GGHV_LINE1689_sec3"]
        else:
            ok = False
    if verbose:
        print(">>> REG1 VERDICT:", "PASS" if ok else "*** FAIL ***")
        for k, v in detail.items():
            print("      %-30s %s" % (k, v))
        print()
    return ok, res, detail


def regression_1b(verbose=True):
    polys, variables, labels, target, _ = gghv_1689_system(include_omitted=True)
    res = lens(polys, variables, labels,
               name="REG1b  CONTROL: twelve equations (incl. the three the paper drops)",
               verbose=verbose, max_subset=3, zname="E")
    merged = [p for p in res["proposals"] if "C3" in p["vars"]]
    ok = (len(merged) == 0)
    if verbose:
        print(">>> REG1b VERDICT:",
              "PASS -- the merge correctly disappears once (Q~)_{-3} is present"
              if ok else "*** FAIL: still proposed %s ***" % merged)
        print()
    return ok, res


# =====================================================================
#  7.  REG2 -- the seven G5body terms and the u-weight grading
# =====================================================================
G5BODY_TERMS = [
    ("d0*dm1*dm4", (1, 0, 0, 1, 0, 0, 1)),
    ("d0*dm2*dm3", (1, 0, 0, 0, 1, 1, 0)),
    ("d1*dm2*dm4", (0, 1, 0, 0, 1, 0, 1)),
    ("d1*dm3^2",   (0, 1, 0, 0, 0, 2, 0)),
    ("d2*dm3*dm4", (0, 0, 1, 0, 0, 1, 1)),
    ("dm1^2*dm3",  (0, 0, 0, 2, 0, 1, 0)),
    ("dm1*dm2^2",  (0, 0, 0, 1, 2, 0, 0)),
]
DOC_WEIGHTS = {"d0": 4, "d1": 3, "d2": 2, "dm1": 5, "dm2": 6, "dm3": 7, "dm4": 8}


def regression_2(verbose=True):
    """Recover the u-weight structure of the seven G5body terms mechanically.
    The lens is NOT told the weights; it solves M w = c*1 and reports the
    solution space.  FACE_KILL_SWEEP.md sec.1 records
    d0=4,d1=3,d2=2,dm1=5,dm2=6,dm3=7,dm4=8 with common u-weight 17."""
    d0, d1, d2, dm1, dm2, dm3, dm4 = sp.symbols("d0 d1 d2 dm1 dm2 dm3 dm4")
    V = [d0, d1, d2, dm1, dm2, dm3, dm4]
    R = sp.Rational
    g5body = (-3*d0*dm1*dm4 - 3*d0*dm2*dm3 - 3*d1*dm2*dm4 - R(3, 2)*d1*dm3**2
              - 3*d2*dm3*dm4 - R(3, 2)*dm1**2*dm3 - R(3, 2)*dm1*dm2**2)
    ed = ExpData([g5body], V, ["G5body"])
    # the 7 terms must be exactly the documented list
    got = sorted(ed.mon_str(m).replace("**", "^") for m in ed.mons)
    want = sorted(n for n, _ in G5BODY_TERMS)
    terms_match = (got == want)
    gs = grading_space(ed)
    wdoc = [DOC_WEIGHTS[str(v)] for v in V]
    contains = grading_contains(gs, wdoc, [17])
    prim = primitive_generator(gs, [str(v) for v in V] + ["c(G5body)"])
    # NULL gradings of G5body alone: weight vectors giving every term weight 0.
    # dim > 0 means the documented u-weights are NOT pinned by G5body by itself.
    # (The documented solution has c = 17 != 0, so c is a nonzero functional on
    # the grading space and its kernel has dimension dim - 1.)
    null_dim = gs["dim"] - 1
    null_gen = None
    if null_dim == 1:
        # a basis vector of the c = 0 subspace, as a primitive integer vector
        B = [list(v) for v in gs["basis"]]
        M = sp.Matrix(B).T                    # columns are basis vectors
        cs = sp.Matrix([[b[-1] for b in B]])  # the c-coordinate of each basis vector
        ker = cs.nullspace()
        if ker:
            vec = M * ker[0]
            rats = [sp.Rational(sp.nsimplify(x)) for x in vec[:len(V)]]
            den = sp.ilcm(*[r.q for r in rats])
            ints = [int(r * den) for r in rats]
            g = 0
            for x in ints:
                g = gcd(g, abs(x))
            if g:
                ints = [x // g for x in ints]
            null_gen = dict(zip([str(v) for v in V], ints))
    per_term = [(name, sum(e * wdoc[i] for i, e in enumerate(exps)))
                for name, exps in G5BODY_TERMS]

    Phi = sp.Symbol("Phi")
    G1 = R(3, 2)*d1*dm1**2 + 3*d2*dm1*dm2 + 3*dm1*dm4 + 3*dm2*dm3
    G2 = -R(3, 2)*d0*dm1**2 + R(3, 2)*d2*dm2**2 + 3*dm2*dm4 + R(3, 2)*dm3**2
    G3 = -3*d0*dm1*dm2 - R(3, 2)*d1*dm2**2 - R(1, 2)*dm1**3 + 3*dm3*dm4
    G5 = Phi + g5body
    ed4 = ExpData([G1, G2, G3, G5], V + [Phi], ["G1", "G2", "G3", "G5"])
    gs4 = grading_space(ed4)
    contains4 = grading_contains(gs4, wdoc + [17], [13, 14, 15, 17])
    prim4 = primitive_generator(gs4, [str(v) for v in V] + ["Phi",
                                                           "c(G1)", "c(G2)", "c(G3)", "c(G5)"])
    ok = bool(terms_match and contains and contains4 and all(w == 17 for _, w in per_term))
    if verbose:
        print("=" * 78)
        print("MONOMIAL LENS  --  REG2  u-weight structure of the seven G5body terms")
        print("-" * 78)
        print("  the 7 input monomials match FACE_KILL_SWEEP sec.1's list: %s" % terms_match)
        print("  LEVEL C grading space {(w,c) : <exp(m),w> = c for every monomial m}:")
        print("     %d constraints, solution space dimension %d  (unique up to scale: %s)"
              % (gs["n_constraints"], gs["dim"], gs["dim"] == 1))
        if prim:
            print("     primitive integer generator recovered from the monomials alone:")
            for k, v in prim.items():
                print("        %-12s %s" % (k, v))
        print("  documented weight vector lies in the space: %s" % contains)
        if null_dim > 0:
            print("  HONEST CAVEAT: the seven G5body monomials ALONE do not pin the")
            print("     weights -- there is a %d-dimensional space of NULL gradings" % null_dim)
            print("     (every term weight 0).  A generator, which has mixed signs so it")
            print("     is a Laurent symmetry only:")
            print("        %s" % null_gen)
            print("     Any w + t*null is an equally valid weighting of G5body.")
        print("  per-term u-weight under the documented vector:")
        for nm, w in per_term:
            print("     %-14s %d" % (nm, w))
        print("  cross-check on the full G-system G1,G2,G3,G5=Phi+G5body:")
        print("     solution space dimension %d; documented (w,Phi=17; 13,14,15,17) in it: %s"
              % (gs4["dim"], contains4))
        if prim4:
            print("     primitive generator:", prim4)
        print(">>> REG2 VERDICT:", "PASS" if ok else "*** FAIL ***")
        print()
    return ok, {"terms_match": terms_match, "dim": gs["dim"],
                "null_dim_G5body": null_dim, "null_generator_G5body": null_gen,
                "unique_up_to_scale": gs["dim"] == 1, "primitive": prim,
                "contains_doc": contains, "per_term": per_term,
                "dim_full_G": gs4["dim"], "contains_doc_full_G": contains4,
                "primitive_full_G": prim4}


# =====================================================================
#  8.  REG3 -- the deliberate NEGATIVE test
# =====================================================================
def regression_3(verbose=True):
    """f1 = a*b^2 + c ;  f2 = a^2*b^4*c - 3 = (a b^2)^2 c - 3 ;  f3 = b + c.
    `b` occurs both inside the product a*b^2 and ON ITS OWN in f3, so merging
    {a,b} is UNSOUND and the tool must refuse.  Positive control: drop f3 and
    the merge must reappear."""
    a, b, c = sp.symbols("a b c")
    bad = [a*b**2 + c, a**2*b**4*c - 3, b + c]
    good = [a*b**2 + c, a**2*b**4*c - 3]
    res_bad = lens(bad, [a, b, c], ["f1", "f2", "f3"],
                   name="REG3  NEGATIVE control (b occurs inside AND outside a*b^2)",
                   verbose=verbose, zname="z")
    res_good = lens(good, [a, b, c], ["f1", "f2"],
                    name="REG3  POSITIVE control (the same system without f3 = b + c)",
                    verbose=verbose, zname="z")
    refused = not any(set(p["vars"]) & {"a", "b"} for p in res_bad["proposals"])
    accepted = any(set(p["vars"]) == {"a", "b"} for p in res_good["proposals"])
    # LEMMA L, executed rather than merely proved: eliminate {a,b} upstairs and
    # {z} downstairs and compare the contractions into Q[c].
    z = sp.Symbol("z")
    down = [p for p in res_good["proposals"] if set(p["vars"]) == {"a", "b"}]
    lemma_l = None
    if down:
        gpolys = down[0]["new_polys"]
        zsym = sp.Symbol(down[0]["z"])
        up_elim = [g for g in sp.groebner(good, a, b, c, order="lex").exprs
                   if not (g.has(a) or g.has(b))]
        dn_elim = [g for g in sp.groebner(gpolys, zsym, c, order="lex").exprs
                   if not g.has(zsym)]
        lemma_l = {
            "I_cap_Qc": [str(sp.factor_list(g)[1] and sp.expand(g)) for g in up_elim],
            "J_cap_Qc": [str(sp.expand(g)) for g in dn_elim],
            "equal": (len(up_elim) == len(dn_elim)
                      and all(sp.expand(u * sp.LC(d, c) - d * sp.LC(u, c)) == 0
                              for u, d in zip(up_elim, dn_elim))),
        }
    ed_bad = ExpData(bad, [a, b, c], ["f1", "f2", "f3"])
    exc, ks, viol = check_exclusivity(ed_bad, [0, 1], [1, 2])
    forced_refusal = (not exc) and len(viol) > 0
    # and the forced application must RAISE, not silently proceed
    raised = False
    try:
        apply_merge(ed_bad, [0, 1], [1, 2], "z")
    except ValueError:
        raised = True
    ok = (refused and accepted and forced_refusal and raised
          and bool(lemma_l and lemma_l["equal"]))
    if verbose:
        print(">>> REG3 VERDICT:", "PASS" if ok else "*** FAIL ***")
        print("      refused on the bad system         : %s" % refused)
        print("      accepted on the good system       : %s" % accepted)
        print("      forced z=a*b^2 rejected by (H1)   : %s" % forced_refusal)
        print("      apply_merge() raised on the force : %s" % raised)
        if lemma_l:
            print("      LEMMA L executed on the positive control:")
            print("         I cap Q[c] (eliminate a,b upstairs) = %s" % lemma_l["I_cap_Qc"])
            print("         J cap Q[c] (eliminate z downstairs) = %s" % lemma_l["J_cap_Qc"])
            print("         equal up to scalars: %s" % lemma_l["equal"])
        if viol:
            print("      refusal witness: %s, monomial %s"
                  % (viol[0]["poly"], viol[0]["monomial"]))
        print()
    return ok, {"refused": refused, "accepted": accepted,
                "forced_refusal": forced_refusal, "raised": raised,
                "lemma_l": lemma_l,
                "witness": viol[0] if viol else None}


# =====================================================================
#  9.  REG4 -- THE REAL QUESTION: R9 / alt-bridge H-system
# =====================================================================
def _import_bigrade():
    if HERE not in sys.path:
        sys.path.insert(0, HERE)
    import bigrade_annotator as ba          # noqa: E402
    return ba


def regression_4(verbose=True, max_subset=8):
    """max_subset=8 makes the LEVEL B scan EXHAUSTIVE over these systems
    (7 and 8 declared variables) -- every subset is tested, none sampled."""
    ba = _import_bigrade()
    Hs = ba._H_generators()                 # loads r9_eliminated_system.json verbatim
    d0, d1, d2, dm1, dm2, dm3, dm4, Phi = ba._gsystem_symbols()
    V = [d0, d1, d2, dm1, dm2, dm3, Phi]    # dm4 already eliminated
    labels = sorted(Hs)
    polys = [Hs[k][0] for k in labels]
    res = lens(polys, V, labels,
               name="REG4  R9 z=1 dm4-eliminated H-system (r9_eliminated_system.json)",
               verbose=verbose, max_subset=max_subset, zname="z")

    same = None
    altpath = os.path.join(HERE, "alt_eliminated_system.json")
    if os.path.exists(altpath):
        with open(altpath) as fh:
            alt = json.load(fh)
        with open(os.path.join(HERE, "r9_eliminated_system.json")) as fh:
            r9 = json.load(fh)
        same = (alt["H"] == r9["H"])

    gens = ba._G_generators()
    glabels = sorted(gens)
    VG = [d0, d1, d2, dm1, dm2, dm3, dm4, Phi]
    resG = lens([gens[k][0] for k in glabels], VG, glabels,
                name="REG4b  the pre-elimination full G-system G1,G2,G3,G5",
                verbose=verbose, max_subset=max_subset, zname="z")

    n_H, n_G = len(res["proposals"]), len(resG["proposals"])
    nb_H = len([d for d in res["lattice"] if d["rank"] >= 2 and not d.get("subsumed")])
    nb_G = len([d for d in resG["lattice"] if d["rank"] >= 2 and not d.get("subsumed")])
    if verbose:
        print(">>> REG4 REPORT (this regression reports; it does not hope):")
        print("      R9 H-system  LEVEL A merges : %d" % n_H)
        print("      R9 H-system  LEVEL B new    : %d  (exhaustive over all subsets)" % nb_H)
        print("      R9 H-system  torus dimension: %d"
              % res["exponent_lattice"]["torus_dim"])
        print("      full G-system LEVEL A merges: %d, LEVEL B new: %d, torus dim: %d"
              % (n_G, nb_G, resG["exponent_lattice"]["torus_dim"]))
        print("      alt_eliminated_system.json H == r9_eliminated_system.json H: %s" % same)
        print("      -> the alt bridge is the SAME symbol-level object; one run covers both.")
        print()
    return {"n_merges_H": n_H, "n_merges_G": n_G,
            "n_levelB_H": nb_H, "n_levelB_G": nb_G,
            "torus_dim_H": res["exponent_lattice"]["torus_dim"],
            "torus_dim_G": resG["exponent_lattice"]["torus_dim"],
            "alt_identical": same, "H": res, "G": resG}


# =====================================================================
# 10.  scalar-level R9 (optional, expensive)
# =====================================================================
def scalar_R9(verbose=True, max_subset=3):
    """The lens at the SCALAR level of the R9 z=1 state -- the level at which a
    latent coordinate would actually help a solve.

    WHY THIS DOES NOT NEED THE (very expensive) y-COEFFICIENT SPLIT.
    bigrade_annotator.build_R3() emits one scalar equation per y-order: the
    y-coefficients of H2,H3,H5 after the state substitution.  Splitting by
    y-degree PARTITIONS terms; it neither creates nor destroys monomials in the
    spare unknowns.  Formally: view the substituted generator as a polynomial in
    the unknowns with coefficients in Q[y, params]; the coefficient of an
    unknown-monomial is a polynomial in y whose j-th coefficient is exactly that
    monomial's coefficient in the j-th scalar equation, so it vanishes iff the
    monomial is absent from EVERY scalar equation.  The union of the supports of
    the scalar equations therefore equals the support of the unsplit expression.
    LEVEL A and LEVEL B read only that union, so they are unaffected -- and the
    unsplit form costs ~100 s instead of the documented multi-hour sympy trap.
    (LEVEL C would differ, since it wants a constant per equation; it is not
    used here.)

    The state ansatz below mirrors bigrade_annotator.build_R3 verbatim; the H
    generators themselves are loaded through ba._H_generators().
    """
    ba = _import_bigrade()
    y = ba.y
    d0, d1, d2, dm1, dm2, dm3, dm4, Phi = ba._gsystem_symbols()
    gamma, r = sp.symbols("gamma r")
    a = sp.symbols("a0 a1 a2 a3 a4")
    g = sp.symbols("g0 g1")
    d2v = sum(a[i] * y**i for i in range(5))
    d1v = sp.Integer(0)
    ev = gamma * (y + 1)**9 * (y - r)
    sigma = sp.expand((y - r)**2 * (g[0] + g[1] * y))
    d0v = sp.expand((d2v**2 + sigma) / 4)
    R = sp.symbols("R0:13")                     # dm2 spare, sub2 cap 12
    S = sp.symbols("S0:15")                     # dm3 spare, sub2 cap 14
    dm2v = sum(R[i] * y**i for i in range(13))
    dm3v = sum(S[i] * y**i for i in range(15))
    subs = {d0: d0v, d1: d1v, d2: d2v, dm1: ev, dm2: dm2v, dm3: dm3v,
            Phi: ba._phi_stripped()}
    Hs = ba._H_generators()
    labels = sorted(Hs)
    polys = [sp.expand(Hs[k][0].xreplace(subs)) for k in labels]

    unknowns = list(R) + list(S)
    params = [gamma, r] + list(a) + list(g)
    out = {}
    res_u = lens(polys, unknowns, labels,
                 name="R9 SCALAR  variables = the %d spare unknowns R0..R12,S0..S14"
                      % len(unknowns),
                 verbose=verbose, max_subset=max_subset, zname="z")
    out["unknowns_only"] = {"n_merges": len(res_u["proposals"]),
                            "n_refusals": len(res_u["refusals"]),
                            "before": res_u["before"],
                            "exponent_lattice": {k: v for k, v in
                                                 res_u["exponent_lattice"].items()
                                                 if k != "null_gradings"}}
    res_a = lens(polys, unknowns + params, labels,
                 name="R9 SCALAR  variables = %d spare unknowns + %d state parameters"
                      % (len(unknowns), len(params)),
                 verbose=verbose, max_subset=max_subset, zname="z")
    out["unknowns_and_params"] = {"n_merges": len(res_a["proposals"]),
                                  "n_refusals": len(res_a["refusals"]),
                                  "before": res_a["before"],
                                  "exponent_lattice": {k: v for k, v in
                                                       res_a["exponent_lattice"].items()
                                                       if k != "null_gradings"}}
    if verbose:
        print(">>> R9 SCALAR SUMMARY")
        for k, v in out.items():
            print("      %-22s LEVEL A merges %d, refusals %d, torus dim %d"
                  % (k, v["n_merges"], v["n_refusals"],
                     v["exponent_lattice"]["torus_dim"]))
        print()
    return out


# =====================================================================
# 11.  main
# =====================================================================
def run_all(verbose=True, deep=False):
    ok1, res1, det1 = regression_1(verbose=verbose)
    ok1b, res1b = regression_1b(verbose=verbose)
    ok2, det2 = regression_2(verbose=verbose)
    ok3, det3 = regression_3(verbose=verbose)
    r4 = regression_4(verbose=verbose)
    # RECORDED expectation for REG4.  Not a hope: the OBSERVED answer, pinned so
    # that any change becomes a loud event.
    ok4 = (r4["n_merges_H"] == 0 and r4["n_merges_G"] == 0
           and r4["n_levelB_H"] == 0 and r4["n_levelB_G"] == 0
           and r4["torus_dim_H"] == 0 and r4["torus_dim_G"] == 0
           and r4["alt_identical"] is True)
    deep_out = scalar_R9(verbose=verbose) if deep else None
    return {
        "REG1_gghv_1689": ok1,
        "REG1b_control_refusal": ok1b,
        "REG2_u_weights": ok2,
        "REG3_negative": ok3,
        "REG4_r9_no_merge": ok4,
        "all": bool(ok1 and ok1b and ok2 and ok3 and ok4),
        "detail": {"reg1": det1, "reg2": det2, "reg3": det3,
                   "reg4": {k: r4[k] for k in
                            ("n_merges_H", "n_merges_G", "n_levelB_H", "n_levelB_G",
                             "torus_dim_H", "torus_dim_G", "alt_identical")}},
        "deep": deep_out,
    }


KEYS = ("REG1_gghv_1689", "REG1b_control_refusal", "REG2_u_weights",
        "REG3_negative", "REG4_r9_no_merge")


def main():
    ap = argparse.ArgumentParser(description="Monomial Lens: latent quotient coordinates")
    ap.add_argument("--quiet", action="store_true",
                    help="run the regressions silently; exit 0 iff all behave as recorded")
    ap.add_argument("--deep", action="store_true",
                    help="ALSO run the scalarised R9 system (minutes)")
    ap.add_argument("--json", metavar="PATH", help="write the verdict dict as JSON")
    args = ap.parse_args()

    if args.quiet:
        import io
        buf, old = io.StringIO(), sys.stdout
        sys.stdout = buf
        try:
            v = run_all(verbose=False, deep=args.deep)
        finally:
            sys.stdout = old
        for k in KEYS:
            print("%-24s %s" % (k, "PASS" if v[k] else "FAIL"))
        if args.json:
            with open(args.json, "w") as fh:
                json.dump({k: v[k] for k in list(KEYS) + ["all", "detail"]},
                          fh, indent=1, default=str)
        sys.exit(0 if v["all"] else 1)

    print("#" * 78)
    print("# MONOMIAL LENS -- latent quotient coordinates in polynomial systems")
    print("#" * 78)
    print()
    v = run_all(verbose=True, deep=args.deep)
    print("#" * 78)
    print("# REGRESSION SUMMARY")
    for k in KEYS:
        print("#   %-24s %s" % (k, "PASS" if v[k] else "*** FAIL ***"))
    print("#   %-24s %s" % ("ALL", "PASS" if v["all"] else "*** FAIL ***"))
    print("#" * 78)
    if args.json:
        with open(args.json, "w") as fh:
            json.dump({k: v[k] for k in list(KEYS) + ["all", "detail"]},
                      fh, indent=1, default=str)
    sys.exit(0 if v["all"] else 1)


if __name__ == "__main__":
    main()
