#!/usr/bin/env python3
"""saturated_cell.py  --  PILOT: one flag-case as ONE saturated scheme.

THE IDEA (FACE_KILL_SWEEP.md sec.6.2, the withdrawn stratum-union objection).
A phase-D "flag case" is a cell `(a_t, b, branch, sigma_zero, d2_zero,
g_zero_levels)` of the residual universe; its ~36 states on average are NOT
independent problems but DEGREE STRATA of one ansatz.  `deg d2 = 3` means
`a3 != 0 AND a4 = 0`.  For a polynomial written at its cell maximum,
`P = p_0 + ... + p_D y^D`, the strata `{deg P = d}` for `d` in the cell's degree
set union to `{(p_dmin,...,p_D) != 0}` -- a QUASI-AFFINE saturated locus
`V(I) \\ V(B)` with `B = <p_dmin,...,p_D>` the endpoint (irrelevant) ideal, tested
by the saturation `I : B^inf`.  That preserves exactly the open conditions the
per-state Rabinowitsch variables enforce; it does not discard them.

    UNIT saturation  ==>  every stratum in the union is empty
                          ==>  the whole flag-case closes at once.

IMPLEMENTATION CAVEATS honoured here (both from sec.6.2):
 (a) the system is built BEFORE any state-specific division by a leading
     coefficient -- no chart is taken, so the "leading coefficient vanishes"
     branch stays inside the scheme; degree-exactness is imposed ONLY as a
     saturation, never as a substitution;
 (b) the pilot is a SMALL MIXED cell (killed + unresolved strata), not the
     largest cell.

TARGET CELL.  `sub2 a7 b3000 T2` (`a_t=7, b=(3,0,0,0), branch T2,
sigma_zero=False, d2_zero=False, g_zero_levels=()`), 10 states:
`deg d2 in {0..4}` x `deg sigma in {7,8}`, `deg e = 10`, `d1 == 0` (T2).
Chosen because (i) it is the smallest sub2 cell whose state set is an exact
PRODUCT OF INTERVALS of degrees (so the stratum union is exactly one saturation,
with no over-cover), (ii) it is MIXED -- 2 of its 10 states are killed in
`state_kill_ledger.json` (`triage/bridge exact GB (UNIT ideal)`, from
`triage_harvest.json:system4`), 8 are unresolved, and (iii) those 2 kills were
produced by a mechanism this pilot can rebuild EXACTLY, so the controls are real.

TWO ENGINES (both necessary conditions; the second contains the first).
  f31  : the master identity `f31 = sum_f Phi^f e^(21-3f) h_f == 0`, top N
         nonzero y-coefficients, marked root reduced mod `q(r)`.  This is the
         literal generator set `triage_harvest.build_sys4_8` used for the two
         known kills, so a state-level reproduction is exact.
  gsys : the full pre-resultant G-system `G1,G2,G3,G5 = G5body+Phi` on stripped
         spare ansaetze at the sub2 caps (12/14/16), built by
         `face_kill_sweep.build_state_system` -- the validated construction.
         Since `<G-system> cap Q[d2,d1,d0,e,Phi] = <f31>` (F37_SATURATION_REPORT
         fact [5]), every y-coefficient of f31 lies in the ideal generated by the
         y-coefficients of the G_i, so the gsys ideal CONTAINS the f31 ideal:
         a gsys kill is implied by an f31 kill, never the reverse.

MODELLING (stated because it bounds every claim made from the output).
  * `e` is FORCED by the cell flags: `v_t(e) = a_t`, `v_{r_j}(e) = b_j`, and
    `deg e = a_t + sum b` holds for every state of this cell, so
    `e = gamma (y+1)^a (y-r)^{sum b}` exactly, `gamma != 0`.  This is cell data,
    not state data -- imposing it does not narrow the flag-case.
  * `sigma` is carried in the `triage_harvest.build_sys4_8` shape
    `sigma = (y-r)^{2 sum b} * G`, `deg G = deg sigma - 2 sum b`, with `G(r) != 0`
    (i.e. `v_r(sigma) = 2 sum b` EXACTLY).  `G(r) != 0` is an ANSATZ assumption
    inherited from that lane, not a cell flag; `--no-sat-Gr` drops it and the
    report quotes both runs.
  * `d2` is a fully generic polynomial of the cell's maximum degree.  No divisor
    structure is imposed on it (the cell does not pin one).

Read-only over every existing artifact.  Writes `saturated_cell.json` only.

Usage:
    python saturated_cell.py --controls          # C1/C1b/C1c/C2 (fast)
    python saturated_cell.py --target            # the saturated-cell ladder
    python saturated_cell.py --gsys              # G-system cost probe
    python saturated_cell.py --all
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import time

import sympy as sp

import convolution_descent as cd
import convolution_elim as ce
import modular_triage as mt

HERE = os.path.dirname(os.path.abspath(__file__)) or "."
OUT_PATH = os.path.join(HERE, "saturated_cell.json")

Y = cd.y
R = sp.Symbol("r")
GAMMA = sp.Symbol("gamma")
Q_COEFFS = [2048, -512, 320, -240, 195]
WSL = ("wsl.exe", "-d", "Ubuntu", "--", "bash", "-lc", "cd $HOME && Singular -q")

TARGET_CELL = dict(a_t=7, b=(3, 0, 0, 0), branch="T2",
                   sigma_zero=False, d2_zero=False, g_zero_levels=())
UNIVERSE = os.path.join(HERE, "phase_d_states_sub2.json")


def qpoly(var):
    return sum(c * var ** (4 - i) for i, c in enumerate(Q_COEFFS))


QR_POLY = sp.Poly(qpoly(R), R)


def qreduce(expr, marked=True):
    """Reduce an expression modulo q(r) (the marked-root relation)."""
    expr = sp.expand(sp.sympify(expr))
    if not marked or expr == 0 or not expr.has(R):
        return expr
    num, den = sp.fraction(sp.together(expr))
    if den.has(R):
        raise ValueError("r in denominator")
    rem = sp.rem(sp.Poly(sp.expand(num), R), QR_POLY).as_expr()
    return sp.cancel(rem / den)


# =====================================================================
#  1.  The cell and its degree profile
# =====================================================================
def load_cell(spec=TARGET_CELL):
    data = json.load(open(UNIVERSE, encoding="utf-8"))
    hits = [c for c in data["cases"]
            if c["a_t"] == spec["a_t"] and tuple(c["b"]) == tuple(spec["b"])
            and c["branch"] == spec["branch"]
            and bool(c["sigma_zero"]) == spec["sigma_zero"]
            and bool(c["d2_zero"]) == spec["d2_zero"]
            and tuple(c["g_zero_levels"]) == tuple(spec["g_zero_levels"])]
    if len(hits) != 1:
        raise SystemExit("FAIL: cell spec matched %d cases, expected 1" % len(hits))
    case = hits[0]
    if case["state_count"] != len(case["states"]):
        raise SystemExit("FAIL: declared state_count %d != %d listed"
                         % (case["state_count"], len(case["states"])))
    return case


def _d(v):
    return None if v in ("-inf", None) else int(v)


def cell_profile(case):
    """Degree sets of d2/d1/sigma/e over the cell; assert the PRODUCT shape.

    The stratum union is a single saturation only if the state set is the full
    product of per-polynomial degree INTERVALS.  If it is not, this fails loud
    rather than silently over-covering the cell.
    """
    keys = ("deg_d2", "deg_d1", "deg_sigma", "deg_e")
    sets = {k: sorted({_d(st[k]) for st in case["states"]},
                      key=lambda x: (x is None, x)) for k in keys}
    for k, vals in sets.items():
        ints = [v for v in vals if v is not None]
        if ints and ints != list(range(min(ints), max(ints) + 1)):
            raise SystemExit("FAIL: %s degrees %s are not an interval" % (k, vals))
    prod = 1
    for vals in sets.values():
        prod *= len(vals)
    if prod != len(case["states"]):
        raise SystemExit("FAIL: cell is not a product of degree intervals "
                         "(%d combinations vs %d states)" % (prod, len(case["states"])))
    return sets


# =====================================================================
#  2.  The saturated ansatz  (built BEFORE any leading-coefficient division)
# =====================================================================
class CellSystem:
    """Polynomials + endpoint ideals + essential nonvanishing for one run."""

    def __init__(self, label, polys, endpoint_ideals, essential, marked, note=""):
        self.label = label
        self.polys = polys                  # d2, d1, sigma, e (sympy)
        self.endpoint_ideals = endpoint_ideals   # [(name, [gens])] -> sat by IDEAL
        self.essential = essential          # [(name, poly)]        -> sat by ELEMENT
        self.marked = marked
        self.note = note


def build_cell_system(case, *, d2_deg_max, d2_deg_min, g_deg_max, g_deg_min,
                      sat_Gr=True, label="cell", sigma_generic=False):
    """The saturated flag-case ansatz.

    `d2_deg_min=None` means the union INCLUDES `d2 == 0` (no endpoint ideal);
    otherwise the endpoint ideal `<a_{dmin},...,a_{dmax}>` encodes exactly
    `deg d2 in [dmin, dmax]`.  Same for `G` (the sigma cofactor).

    NOTHING is divided by a leading coefficient anywhere in here.
    """
    a_t = case["a_t"]
    b = tuple(case["b"])
    sumb = sum(b)
    marked = sumb > 0
    if sum(1 for x in b if x > 0) > 1:
        raise SystemExit("FAIL: cell has >1 marked root; this pilot handles 0 or 1")

    root_factor = (Y - R) ** sumb if marked else sp.Integer(1)
    e = sp.expand(GAMMA * (Y + 1) ** a_t * root_factor)
    if sp.Poly(e, Y).degree() != _d(case["states"][0]["deg_e"]):
        raise SystemExit("FAIL: forced e has degree %d but the cell records deg_e=%s"
                         % (sp.Poly(e, Y).degree(), case["states"][0]["deg_e"]))

    acoef = tuple(sp.symbols("a0:%d" % (d2_deg_max + 1)))
    d2 = sum(c * Y ** i for i, c in enumerate(acoef))
    d1 = sp.Integer(0) if case["branch"] == "T2" else None
    if d1 is None:
        raise SystemExit("FAIL: this pilot only builds T2 cells (d1 == 0)")

    endpoint = []
    if d2_deg_min is not None:
        endpoint.append(("d2:deg in [%d,%d]" % (d2_deg_min, d2_deg_max),
                         list(acoef[d2_deg_min:d2_deg_max + 1])))
    essential = [("gamma != 0", GAMMA)]

    if sigma_generic:
        # NO pattern-B divisor structure on sigma at all: the honest cell,
        # relaxed further than the lane that produced the known kills.
        smax = g_deg_max + 2 * sumb
        smin = None if g_deg_min is None else g_deg_min + 2 * sumb
        scoef = tuple(sp.symbols("s0:%d" % (smax + 1)))
        sigma = sum(c * Y ** i for i, c in enumerate(scoef))
        if smin is not None:
            endpoint.append(("sigma:deg in [%d,%d]" % (smin, smax),
                             list(scoef[smin:smax + 1])))
        note = ("e = gamma (y+1)^%d (y-r)^%d ; sigma GENERIC deg <= %d ; "
                "d2 generic deg <= %d ; d1 = 0" % (a_t, sumb, smax, d2_deg_max))
    else:
        gcoef = tuple(sp.symbols("g0:%d" % (g_deg_max + 1)))
        G = sum(c * Y ** i for i, c in enumerate(gcoef))
        sigma = sp.expand(((Y - R) ** (2 * sumb) if marked else sp.Integer(1)) * G)
        if g_deg_min is not None:
            endpoint.append(("G:deg in [%d,%d]" % (g_deg_min, g_deg_max),
                             list(gcoef[g_deg_min:g_deg_max + 1])))
        if sat_Gr and marked:
            essential.append(("G(r) != 0  [v_r(sigma) = %d exactly]" % (2 * sumb),
                              qreduce(G.subs(Y, R), marked)))
        note = ("e = gamma (y+1)^%d (y-r)^%d ; sigma = (y-r)^%d G, deg G <= %d ; "
                "d2 generic deg <= %d ; d1 = 0"
                % (a_t, sumb, 2 * sumb, g_deg_max, d2_deg_max))
    return CellSystem(label, dict(d2=d2, d1=d1, sigma=sigma, e=e),
                      endpoint, essential, marked, note)


def strata_covered(case, cs, d2_deg_max, d2_deg_min, g_deg_max, g_deg_min):
    """Which of the cell's states this saturated locus is the union of."""
    sumb = sum(case["b"])
    out = []
    for st in case["states"]:
        dd2, dsig = _d(st["deg_d2"]), _d(st["deg_sigma"])
        degG = None if dsig is None else dsig - 2 * sumb
        lo2 = 0 if d2_deg_min is None else d2_deg_min
        loG = 0 if g_deg_min is None else g_deg_min
        if dd2 is not None and lo2 <= dd2 <= d2_deg_max and \
           degG is not None and loG <= degG <= g_deg_max:
            out.append({"deg_d2": dd2, "deg_sigma": dsig, "deg_G": degG})
    return out


# =====================================================================
#  3.  Engine A -- the f31 master identity
# =====================================================================
def f31_generators(cs, ncoeff=8, top=260, floor=195):
    """Top `ncoeff` nonzero master coefficients, reduced mod q(r)."""
    ans = cd.build_ansatz(d2=cs.polys["d2"], d1=cs.polys["d1"],
                          e=cs.polys["e"], sigma=cs.polys["sigma"])
    eng = cd.ConvolutionDescent(ans, c=ce.DEFAULT_C)
    gens, degrees = [], []
    for dgr in range(top, floor - 1, -1):
        c = qreduce(eng.master_coefficient(dgr), cs.marked)
        if c != 0:
            gens.append(sp.expand(c))
            degrees.append(dgr)
        if len(gens) >= ncoeff:
            break
    return gens, degrees


# =====================================================================
#  4.  Engine B -- the full G-system (face_kill_sweep.build_state_system)
# =====================================================================
def gsys_generators(cs, window="sub2"):
    import face_kill_sweep as fks
    system = fks.build_state_system(cs.label, cs.polys, window,
                                    notes="saturated_cell pilot", material=None)
    gens = [sp.expand(eq.expr) for eq in system.eqs if eq.expr != 0]
    return gens, system


# =====================================================================
#  5.  Singular:  I : B1^inf : B2^inf : <f>^inf  ,  then unit test
# =====================================================================
def poly_to_singular_exact(expr, gens):
    """INTEGER-coefficient Singular text (Singular parses `gm^8/N` as
    `gm^(8/N)`, so rationals must be cleared, never emitted)."""
    expr = sp.cancel(sp.sympify(expr))
    if expr == 0:
        return "0"
    num, den = sp.fraction(sp.together(expr))
    dpoly = sp.Poly(sp.expand(den), *gens)
    if dpoly.total_degree() != 0:
        raise ValueError("non-constant denominator: %s" % den)
    poly = sp.Poly(sp.expand(num), *gens)
    L = sp.Integer(1)
    for c in poly.coeffs():
        L = sp.ilcm(L, sp.denom(c))
    terms = []
    for monom, coeff in poly.terms():
        scaled = sp.nsimplify(coeff * L)
        if not scaled.is_Integer:                 # never truncate (SERIALIZER trap)
            raise ValueError("non-integer coefficient %s after clearing" % scaled)
        c = int(scaled)
        if c == 0:
            continue
        factors = [str(c)] if (c != 1 or all(e == 0 for e in monom)) else []
        for g, e in zip(gens, monom):
            if e == 1:
                factors.append(g.name)
            elif e > 1:
                factors.append("%s^%d" % (g.name, e))
        terms.append("*".join(factors) if factors else str(c))
    return ("+".join(terms)).replace("+-", "-") or "0"


def saturated_program(gens, ring_vars, endpoint_ideals, essential, char=0):
    """`ideal I` -> iterated `sat(.,B)[1]` -> `std` -> unit test + dim."""
    def emit(expr):
        if char == 0:
            return poly_to_singular_exact(expr, ring_vars)
        return mt.poly_to_singular_modp(expr, ring_vars, char)

    lines = ['LIB "elim.lib";',
             "ring Rg = %d,(%s),dp;" % (char, ",".join(v.name for v in ring_vars))]
    names = []
    for i, g in enumerate(gens):
        s = emit(g)
        if s == "0":
            continue
        lines.append("poly f%d = %s;" % (i, s))
        names.append("f%d" % i)
    lines.append("ideal I = %s;" % (",".join(names) if names else "0"))
    lines.append("ideal Is = I;")
    for j, (_name, bgens) in enumerate(endpoint_ideals):
        txt = ",".join(emit(b) for b in bgens)
        lines.append("ideal B%d = %s;" % (j, txt))
        lines.append("Is = sat(Is,B%d)[1];" % j)
    for j, (_name, f) in enumerate(essential):
        lines.append("poly s%d = %s;" % (j, emit(f)))
        lines.append("Is = sat(Is,s%d)[1];" % j)
    lines.append("ideal G = std(Is);")
    lines.append("int u = (reduce(1,G)==0);")
    lines.append('"@@UNIT";')
    lines.append("u;")
    lines.append('"@@DIM";')
    lines.append("dim(G);")
    lines.append("quit;")
    return "\n".join(lines) + "\n"


def run_singular(program, timeout):
    t0 = time.monotonic()
    try:
        cp = subprocess.run(WSL, input=program, text=True, encoding="utf-8",
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                            timeout=timeout, check=False)
    except subprocess.TimeoutExpired:
        return {"status": "timeout", "verdict": "TIMEOUT", "unit": None,
                "dim": None, "wall": round(time.monotonic() - t0, 2)}
    out = (cp.stdout or "").replace("\x00", "")
    err = (cp.stderr or "").replace("\x00", "")
    import re
    um = re.search(r"@@UNIT\s*\r?\n\s*(-?\d+)", out + "\n" + err)
    dm = re.search(r"@@DIM\s*\r?\n\s*(-?\d+)", out + "\n" + err)
    unit = None if um is None else bool(int(um.group(1)))
    return {"status": "ok" if cp.returncode == 0 else "proc_error",
            "verdict": "UNIT" if unit else ("PROPER" if unit is False else "PARSE_FAIL"),
            "unit": unit, "dim": None if dm is None else int(dm.group(1)),
            "wall": round(time.monotonic() - t0, 2),
            "stderr": err.strip()[:400], "stdout_tail": out.strip()[-400:]}


def solve(cs, gens, *, char=0, timeout=600.0, extra_gens=()):
    members = list(gens) + list(extra_gens)
    if cs.marked:
        members = members + [qpoly(R)]
    ring_vars = mt.ring_vars_of(members,
                                extra=[b for _n, bg in cs.endpoint_ideals for b in bg]
                                + [GAMMA])
    prog = saturated_program(members, ring_vars, cs.endpoint_ideals,
                             cs.essential, char=char)
    res = run_singular(prog, timeout)
    res["n_gens"] = len(members)
    res["n_ring_vars"] = len(ring_vars)
    res["ring_vars"] = [v.name for v in ring_vars]
    res["program_bytes"] = len(prog)
    res["char"] = char
    return res, prog


# =====================================================================
#  6.  Runs
# =====================================================================
def _report(tag, res, expect=None):
    ok = "" if expect is None else ("  [expected %s -> %s]" % (
        expect, "OK" if res["verdict"] == expect else "*** MISMATCH ***"))
    print("  %-52s %-10s dim=%-4s %7.2fs  vars=%-3s gens=%s%s"
          % (tag, res["verdict"], res.get("dim"), res["wall"],
             res.get("n_ring_vars"), res.get("n_gens"), ok), flush=True)
    return res


def run_controls(case, ncoeff, timeout):
    rows = []
    print("\nCONTROL C1 -- reproduce the two LEDGER KILLS of this cell")
    print("  (state_kill_ledger.json: 'triage/bridge exact GB (UNIT ideal)',")
    print("   source triage_harvest.json:system4 -> UNIT, 1.14s / 1.52s)")
    for dd2 in (0, 1):
        cs = build_cell_system(case, d2_deg_max=dd2, d2_deg_min=None,
                               g_deg_max=1, g_deg_min=None,
                               label="C1_state_dd2%d_dsig7" % dd2)
        gens, degs = f31_generators(cs, ncoeff=ncoeff)
        res, _ = solve(cs, gens, char=0, timeout=timeout)
        res.update(kind="control-C1", label=cs.label, expect="UNIT",
                   note=cs.note, coeff_degrees=degs,
                   claim="reproduces ledger kill sub2T2_a7_b3000_dd2%d_dsig7" % dd2)
        rows.append(_report(cs.label + " (as-built strata)", res, "UNIT"))

    print("\nCONTROL C1b -- the SAME two strata, but DEGREE-EXACT (lc saturated)")
    for dd2 in (0, 1):
        cs = build_cell_system(case, d2_deg_max=dd2, d2_deg_min=dd2,
                               g_deg_max=1, g_deg_min=1,
                               label="C1b_exact_dd2%d_dsig7" % dd2)
        gens, degs = f31_generators(cs, ncoeff=ncoeff)
        res, _ = solve(cs, gens, char=0, timeout=timeout)
        res.update(kind="control-C1b", label=cs.label, expect="UNIT",
                   note=cs.note, coeff_degrees=degs)
        rows.append(_report(cs.label, res, "UNIT"))

    print("\nCONTROL C1c -- the SATURATED UNION of those two known-empty strata")
    print("  (endpoint ideal <a0,a1>: exactly deg d2 in {0,1}; must be EMPTY)")
    cs = build_cell_system(case, d2_deg_max=1, d2_deg_min=0,
                           g_deg_max=1, g_deg_min=1, label="C1c_union_dd2le1_dsig7")
    gens, degs = f31_generators(cs, ncoeff=ncoeff)
    res, _ = solve(cs, gens, char=0, timeout=timeout)
    res.update(kind="control-C1c", label=cs.label, expect="UNIT", note=cs.note,
               coeff_degrees=degs,
               claim="union of the two ledger-killed strata; UNIT = closure reproduced")
    rows.append(_report(cs.label, res, "UNIT"))

    print("\nCONTROL C2 -- a state recorded NOT empty must NOT come out UNIT")
    print("  (modular_triage.json system2 a8_dd20_dd10_dsig5: PROPER dim 2, 3 primes)")
    subs = {s["name"]: s for s in mt.build_system2()}
    ss = subs["a8_dd20_dd10_dsig5"]
    for p in (10007, 10009):
        ring_vars = mt.ring_vars_of(ss["gens"], extra=list(ss["ring_vars"]))
        prog = saturated_program(ss["gens"], ring_vars, [], [], char=p)
        res = run_singular(prog, timeout)
        res.update(kind="control-C2", label="a8_dd20_dd10_dsig5@p%d" % p,
                   expect="PROPER", n_ring_vars=len(ring_vars),
                   n_gens=len(ss["gens"]), note=ss["note"])
        rows.append(_report(res["label"], res, "PROPER"))
    return rows


def run_target(case, ncoeff, timeout, sat_Gr=True, sigma_generic=False,
               chars=(0,), rows_filter=()):
    """The saturated-cell ladder: widen the d2 stratum union, then sigma, then all.

    The generator set is built ONCE per ladder entry and then solved at every
    requested characteristic -- `char = 0` is the exact-Q kill, `char = p > 0`
    is mod-p RECONNAISSANCE (empty over Fbar_p is a prediction, never a kill).
    """
    rows = []
    base = "genSig" if sigma_generic else ("satGr" if sat_Gr else "noGr")
    if ncoeff != 8:
        base += "_n%d" % ncoeff
    mk = lambda **kw: build_cell_system(case, sat_Gr=sat_Gr,
                                        sigma_generic=sigma_generic, **kw)
    ladder = ([("T_dd2le%d_dsig7", d, 0, 1, 1, "target-row-dsig7") for d in (1, 2, 3, 4)]
              + [("T_dd2le%d_dsig8", d, 0, 2, 2, "target-row-dsig8") for d in (1, 2, 3, 4)]
              + [("T_dd2le%d_dsigBOTH", d, 0, 2, 1, "target-row-both") for d in (1, 2, 3)]
              + [("TARGET_full_cell", 4, 0, 2, 1, "target-full-cell")])
    if rows_filter:
        want = set(rows_filter)
        ladder = [L for L in ladder
                  if "%d:%d:%d" % (L[1], L[4], L[3]) in want]
        if not ladder:
            raise SystemExit("FAIL: --rows matched no ladder entry")
    print("\nTARGET -- saturated stratum unions in cell a7_b3000_T2  [%s]" % base)
    for name, dmax, dmin, gmax, gmin, kind in ladder:
        stem = (name % dmax) if "%d" in name else name
        cs = mk(d2_deg_max=dmax, d2_deg_min=dmin, g_deg_max=gmax, g_deg_min=gmin,
                label="%s_%s" % (stem, base))
        t0 = time.time()
        gens, degs = f31_generators(cs, ncoeff=ncoeff)
        build_s = round(time.time() - t0, 1)
        for ch in chars:
            label = "%s_%s%s" % (stem, base, "" if ch == 0 else "_p%d" % ch)
            res, _ = solve(cs, gens, char=ch, timeout=timeout)
            res.update(kind=kind, label=label, note=cs.note, coeff_degrees=degs,
                       build_seconds=build_s,
                       strata=strata_covered(case, cs, dmax, dmin, gmax, gmin))
            rows.append(_report(label, res))
    return rows


def run_gsys(case, timeout, char=0, d2_deg_max=4, g_deg_max=2):
    """The G-system engine (face_kill_sweep.build_state_system) -- COST PROBE."""
    rows = []
    print("\nG-SYSTEM ENGINE (G1,G2,G3,G5body+Phi, spares at sub2 caps 12/14/16)")
    for label, dmax, dmin, gmax, gmin in (
            ("GS_state_dd20_dsig7", 0, None, 1, None),
            ("GS_union_dd2le1_dsig7", 1, 0, 1, 1),
            ("GS_full_cell", d2_deg_max, 0, g_deg_max, 1)):
        cs = build_cell_system(case, d2_deg_max=dmax, d2_deg_min=dmin,
                               g_deg_max=gmax, g_deg_min=gmin, label=label)
        t0 = time.time()
        gens, system = gsys_generators(cs)
        build_s = round(time.time() - t0, 2)
        res, _ = solve(cs, gens, char=char, timeout=timeout)
        res.update(kind="gsys", label=label, note=cs.note, build_seconds=build_s,
                   n_spare_unknowns=len(system.vars))
        print("    build %.2fs, %d equations, %d spare unknowns"
              % (build_s, len(gens), len(system.vars)), flush=True)
        rows.append(_report(label, res))
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--controls", action="store_true")
    ap.add_argument("--target", action="store_true")
    ap.add_argument("--gsys", action="store_true")
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--no-sat-Gr", action="store_true",
                    help="drop the inherited v_r(sigma) = 2*sum(b) EXACTNESS assumption")
    ap.add_argument("--sigma-generic", action="store_true",
                    help="drop the pattern-B divisor structure on sigma entirely "
                         "(sigma fully generic of the cell's max degree)")
    ap.add_argument("--ncoeff", type=int, default=8)
    ap.add_argument("--timeout", type=float, default=900.0)
    ap.add_argument("--gsys-char", type=int, default=10007)
    ap.add_argument("--rows", default="",
                    help="comma list of ladder entries as dmax:gmin:gmax, "
                         "e.g. 2:1:2 = deg d2 <= 2 and deg sigma in {7,8}")
    ap.add_argument("--chars", default="0",
                    help="comma list of characteristics: 0 = exact Q (a kill), "
                         "p > 0 = mod-p RECONNAISSANCE only")
    ap.add_argument("--out", default=OUT_PATH,
                    help="artifact path (use a distinct one for parallel runs)")
    args = ap.parse_args()
    out_path = args.out
    if not (args.controls or args.target or args.gsys or args.all):
        args.all = True

    print("=" * 78)
    print("SATURATED FLAG-CASE SCHEME -- pilot on sub2 a7_b3000_T2")
    print("=" * 78)
    case = load_cell()
    prof = cell_profile(case)
    print("cell: a_t=%d b=%s %s sigma_zero=%s d2_zero=%s gz=%s"
          % (case["a_t"], case["b"], case["branch"], case["sigma_zero"],
             case["d2_zero"], case["g_zero_levels"]))
    print("states: %d   degree profile: %s" % (len(case["states"]), prof))

    out = {"schema": "d2-saturated-cell-v1",
           "cell": {k: (list(v) if isinstance(v, (list, tuple)) else v)
                    for k, v in TARGET_CELL.items()},
           "state_count": len(case["states"]),
           "degree_profile": {k: v for k, v in prof.items()},
           "ncoeff": args.ncoeff, "rows": []}

    if args.controls or args.all:
        out["rows"] += run_controls(case, args.ncoeff, args.timeout)
    if args.target or args.all:
        out["rows"] += run_target(case, args.ncoeff, args.timeout,
                                  sat_Gr=not args.no_sat_Gr,
                                  sigma_generic=args.sigma_generic,
                                  chars=tuple(int(c) for c in args.chars.split(",")),
                                  rows_filter=tuple(
                                      x for x in args.rows.split(",") if x))
    if args.gsys or args.all:
        out["rows"] += run_gsys(case, args.timeout, char=args.gsys_char)

    # MERGE, never clobber: a section run alone must not drop the other
    # sections' evidence from the artifact.
    if os.path.exists(out_path):
        try:
            prev = json.load(open(out_path, encoding="utf-8"))
        except Exception:
            prev = {}
        fresh = {r["label"] for r in out["rows"] if "label" in r}
        keep = [r for r in prev.get("rows", []) if r.get("label") not in fresh]
        out["rows"] = keep + out["rows"]

    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=2, sort_keys=True, default=str)
    print("\nwrote", os.path.basename(out_path))

    bad = [r for r in out["rows"]
           if r.get("expect") and r["verdict"] != r["expect"]]
    if bad:
        print("*** CONTROL MISMATCH on %d run(s) -- the pipeline is NOT validated ***"
              % len(bad))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
