"""
t5_block1_dehom_gen.py — dehomogenized (e0=1) probes for the weight-cone ideals
of the T5 case tree (T5_NP.md), f31 subcase-2, a=0 stratum, over F_32003.

Structure used: assigning window coefficients the weights of their parent
variables (a_i:2, b_i:3, c_i:4, e_i:5) makes every t-coefficient of h_f(d~)
weighted-homogeneous (weight 20-2f). The a=0 stratum has e0 != 0, and since
gcd(5, 32002) = 1 the map s -> s^5 is a bijection on F_p^*, so the weighted
scaling lets us set e0 = 1 EXACTLY over this prime (orbit-wise bijection).
This applies to the pure-h ideals: block1 (t^30 | h_0), A0 (h_0 == 0),
A0+B1 (branch ii), A0+A1 (branch iii premise) — NOT to cascade blocks >= 2,
which mix in the fixed (weight-0) u.

Probes (slimgb, 31 vars, e0 eliminated):
  Q1 = block1            : 30 eqs deg 10   -> dim of the generic-branch cone
  Q2 = A0                : 41 eqs          -> curve-on-h31 stratum (P1 analog)
  Q3 = A0 + B1           : 71 eqs          -> branch (ii) necessary
"""
import re

hs = {}
for m in re.finditer(r'h_(\d) \(weight \d+, dm1-power \d+\) = (.+)',
                     open('f31_graded.txt').read()):
    hs[int(m.group(1))] = m.group(2).replace('**', '^')

AV = [f'a{i}' for i in range(5)]
BV = [f'b{i}' for i in range(7)]
CV = [f'c{i}' for i in range(9)]
EV = [f'e{i}' for i in range(1, 11)]          # e0 = 1 substituted out
allv = AV + BV + CV + EV

def window(cs, first=None):
    parts = ([first] if first else [])
    parts += [f'{c}*t^{i}' for i, c in enumerate(cs, start=1 if first else 0)]
    return '+'.join(parts)

sc = f"""// generated by t5_block1_dehom_gen.py — do not edit by hand
option(prot);
ring R=32003,(d2,d1,d0,dm1,{','.join(allv)},t),dp;
poly D2={'+'.join(f'a{i}*t^{i}' if i else 'a0' for i in range(5))};
poly D1={'+'.join(f'b{i}*t^{i}' if i else 'b0' for i in range(7))};
poly D0={'+'.join(f'c{i}*t^{i}' if i else 'c0' for i in range(9))};
poly E =1+{'+'.join(f'e{i}*t^{i}' for i in range(1, 11))};
poly H0={hs[0]};
H0=subst(H0,d2,D2,d1,D1,d0,D0,dm1,E);
poly H1={hs[1]};
H1=subst(H1,d2,D2,d1,D1,d0,D0,dm1,E);

int i;
matrix C0=coeffs(H0,t);
matrix C1=coeffs(H1,t);
"nrows C0,C1 (expect 41,37):",nrows(C0),nrows(C1);

ideal B1; for(i=1;i<=30;i++){{ B1[i]=C0[i,1]; }}
ideal A0; for(i=1;i<=nrows(C0);i++){{ A0[i]=C0[i,1]; }}
ideal BB1; for(i=1;i<=30;i++){{ BB1[i]=C1[i,1]; }}

"=== Q1: block1 (t^30|h_0), e0=1, 30 eqs ===";
ideal S1=slimgb(B1);
"Q1 GB size:",size(S1),"  dim (true = this - 5):",dim(S1);
if(S1[1]==1){{ "*** Q1 EMPTY: generic branch (i) first block already dead ***"; }}

"=== Q2: h_0(d~)==0, e0=1, 41 eqs ===";
ideal S2=slimgb(A0);
"Q2 GB size:",size(S2),"  dim (true = this - 5):",dim(S2);
if(S2[1]==1){{ "*** Q2 EMPTY: branches (ii),(iii) dead ***"; }}

"=== Q3: h_0==0 + t^30|h_1, e0=1, 71 eqs ===";
ideal J3=A0,BB1;
ideal S3=slimgb(J3);
"Q3 GB size:",size(S3),"  dim (true = this - 5):",dim(S3);
if(S3[1]==1){{ "*** Q3 EMPTY: branch (ii) dead ***"; }}
quit;
"""

open('t5_block1_dehom.sing', 'w').write(sc)
print("wrote t5_block1_dehom.sing")
