"""
t5_block1_homog_gen.py — homogeneous variant of the block-1 probe.

The 30 equations of block 1 (t-coeffs 0..29 of h_0(d~)) are weighted-
homogeneous of weight 20 under a_i:2, b_i:3, c_i:4, e_i:5. Compute their GB in
a wp-weighted ring (Hilbert-driven advantages), report dim, then saturate by
e0 to discard the a>0 (e0=0) components and report the a=0 stratum dimension.
"""
import re

hs = {}
for m in re.finditer(r'h_(\d) \(weight \d+, dm1-power \d+\) = (.+)',
                     open('f31_graded.txt').read()):
    hs[int(m.group(1))] = m.group(2).replace('**', '^')

AV = [f'a{i}' for i in range(5)]
BV = [f'b{i}' for i in range(7)]
CV = [f'c{i}' for i in range(9)]
EV = [f'e{i}' for i in range(11)]
allv = AV + BV + CV + EV
wts = [2]*5 + [3]*7 + [4]*9 + [5]*11

def wpoly(cs):
    return '+'.join(f'{c}*t^{i}' if i else c for i, c in enumerate(cs))

sc = f"""// generated by t5_block1_homog_gen.py — do not edit by hand
option(prot);
// helper ring for substitution (t present)
ring Rh=32003,(d2,d1,d0,dm1,{','.join(allv)},t),dp;
poly D2={wpoly(AV)};
poly D1={wpoly(BV)};
poly D0={wpoly(CV)};
poly E ={wpoly(EV)};
poly H0={hs[0]};
H0=subst(H0,d2,D2,d1,D1,d0,D0,dm1,E);
matrix C0=coeffs(H0,t);
ideal B1;
int i;
for(i=1;i<=30;i++){{ B1[i]=C0[i,1]; }}

// weighted ring, window vars only, homogeneous wrt wp
ring Rw=32003,({','.join(allv)}),wp({','.join(map(str, wts))});
ideal B1=imap(Rh,B1);
"homogeneous check (0 = all homog):";
for(i=1;i<=30;i++){{ if(homog(B1[i])==0){{ "gen",i,"NOT homog"; }} }}
"=== std on weighted-homogeneous block 1 (30 eqs) ===";
ideal S=std(B1);
"GB size:",size(S),"  dim (cone, all strata):",dim(S);
"=== saturating by e0 (a=0 stratum) ===";
LIB "elim.lib";
ideal T=sat(S,e0)[1];
ideal ST=std(T);
"sat GB size:",size(ST),"  dim:",dim(ST);
if(ST[1]==1){{ "*** a=0 stratum of block 1 EMPTY over F_p ***"; }}
quit;
"""

open('t5_block1_homog.sing', 'w').write(sc)
print("wrote t5_block1_homog.sing")
