"""
t5_branch23_gen.py — Singular probe for Newton-polygon branches (ii)/(iii)
(T5_NP.md, a=0 stratum, f31 subcase-2).

Branch (ii) needs h_0(d~) == 0 identically AND t^30 | h_1(d~), h_1(d~) != 0.
Branch (iii) needs h_0 == h_1 == 0 identically AND t^30 | h_2, h_2 != 0.

This probe tests the successive necessary ideals over F_32003 (e0 != 0 via
Rabinowitsch), reporting dim after each addition:
  P1 = { all 41 t-coeffs of h_0(d~) } + (z*e0-1)
  P2 = P1 + { t-coeffs t^0..t^29 of h_1(d~) }          <- branch (ii) necessary
  P3 = P1 + { all 37 t-coeffs of h_1(d~) }             <- branch (iii) premise
  P4 = P3 + { t-coeffs t^0..t^29 of h_2(d~) }          <- branch (iii) necessary
If P2 forces h_1(d~) == 0 (i.e. dim P2 == dim P3 and the extra h_1 coeffs lie
in P2's radical) branch (ii) collapses into (iii); if P4 is empty (or forces
h_2 == 0, contradicting the Theorem's case-(iv) exclusion), branch (iii) dies.

NOTE on dim: ring has 4 parse vars (d2,d1,d0,dm1) + t unused by the ideals,
z consumed; reported dim = true stratum dim + 5.
"""
import re

hs = {}
for m in re.finditer(r'h_(\d) \(weight \d+, dm1-power \d+\) = (.+)',
                     open('f31_graded.txt').read()):
    hs[int(m.group(1))] = m.group(2).replace('**', '^')

AV = [f'a{i}' for i in range(5)]
BV = [f'b{i}' for i in range(7)]
CV = [f'c{i}' for i in range(9)]
EV = [f'e{i}' for i in range(11)]
allv = AV + BV + CV + EV

def window(cs):
    return '+'.join(f'{c}*t^{i}' if i else c for i, c in enumerate(cs))

sc = f"""// generated by t5_branch23_gen.py — do not edit by hand
option(prot);
ring R=32003,(d2,d1,d0,dm1,{','.join(allv)},z,t),dp;
poly D2={window(AV)};
poly D1={window(BV)};
poly D0={window(CV)};
poly E ={window(EV)};
poly H0={hs[0]};
H0=subst(H0,d2,D2,d1,D1,d0,D0,dm1,E);
poly H1={hs[1]};
H1=subst(H1,d2,D2,d1,D1,d0,D0,dm1,E);
poly H2={hs[2]};
H2=subst(H2,d2,D2,d1,D1,d0,D0,dm1,E);

int i;
matrix C0=coeffs(H0,t);
matrix C1=coeffs(H1,t);
matrix C2=coeffs(H2,t);
"nrows C0,C1,C2 (expect <=41,37,33):",nrows(C0),nrows(C1),nrows(C2);

ideal A0; for(i=1;i<=nrows(C0);i++){{ A0[i]=C0[i,1]; }}      // h_0 == 0
ideal B1; for(i=1;i<=30;i++){{ B1[i]=C1[i,1]; }}             // t^30 | h_1
ideal A1; for(i=1;i<=nrows(C1);i++){{ A1[i]=C1[i,1]; }}      // h_1 == 0
ideal B2; for(i=1;i<=30;i++){{ B2[i]=C2[i,1]; }}             // t^30 | h_2
ideal Iaux=z*e0-1;

"=== P1: h_0(d~)==0 (41 eqs) + e0!=0 ===";
ideal J1=A0,Iaux;
ideal S1=std(J1);
"P1 GB size:",size(S1),"  dim(true=this-5):",dim(S1);
if(S1[1]==1){{ "*** P1 EMPTY: no window curve on h31=0 with e0!=0 — branches (ii),(iii) both dead ***"; }}

"=== P2: P1 + t^30|h_1 (30 eqs) ===";
ideal J2=A0,B1,Iaux;
ideal S2=std(J2);
"P2 GB size:",size(S2),"  dim(true=this-5):",dim(S2);
if(S2[1]==1){{ "*** P2 EMPTY: branch (ii) dead ***"; }}

"=== P3: h_0==0, h_1==0 + e0!=0 ===";
ideal J3=A0,A1,Iaux;
ideal S3=std(J3);
"P3 GB size:",size(S3),"  dim(true=this-5):",dim(S3);
if(S3[1]==1){{ "*** P3 EMPTY: branch (iii) premise dead ***"; }}

"=== P4: P3 + t^30|h_2 (30 eqs) ===";
ideal J4=A0,A1,B2,Iaux;
ideal S4=std(J4);
"P4 GB size:",size(S4),"  dim(true=this-5):",dim(S4);
if(S4[1]==1){{ "*** P4 EMPTY: branch (iii) dead ***"; }}
quit;
"""

open('t5_branch23.sing', 'w').write(sc)
print("wrote t5_branch23.sing")
