"""
t5_cascade_gen.py — generate the Singular driver for the T5 g-cascade probe
(branch (i), a=0 stratum, f31 subcase-2 windows; see T5_NP.md).

Emits t5_cascade.sing which:
  * builds h_0, h_1 substituted with the stripped window polynomials in t
    (d~2: a0..a4, d~1: b0..b6, d~0: c0..c8, d~-1=e: e0..e10),
  * forms block 1 = coeffs t^0..t^29 of h_0(d~)          (30 eqs, deg 10)
  *       block 2 = coeffs t^0..t^29 of e^3 g_1 + u h_1  (30 eqs, deg 13)
    where g_1 = h_0(d~)/t^30 and u = -(quartic at y=t-1)/6630,
  * imposes a=0 via Rabinowitsch z*e0 = 1,
  * runs std on block 1 (reports dim), then on blocks 1+2.

NOTE on dim: the ring carries 6 auxiliary vars beyond the 32 window unknowns
(d2,d1,d0,dm1 used only for parsing+subst, and t; z is consumed by z*e0-1),
so reported dim = (true stratum dim) + 5.

Run:  python t5_cascade_gen.py
      wsl -e bash -c "cd /mnt/c/.../d2_plane_72_108 && Singular -q t5_cascade.sing"
"""
import re

hs = {}
for m in re.finditer(r'h_(\d) \(weight \d+, dm1-power \d+\) = (.+)',
                     open('f31_graded.txt').read()):
    hs[int(m.group(1))] = m.group(2).replace('**', '^')

AV = [f'a{i}' for i in range(5)]
BV = [f'b{i}' for i in range(7)]
CV = [f'c{i}' for i in range(9)]
EV = [f'e{i}' for i in range(11)]
allv = AV + BV + CV + EV

def window(cs):
    return '+'.join(f'{c}*t^{i}' if i else c for i, c in enumerate(cs))

sc = f"""// generated by t5_cascade_gen.py — do not edit by hand
option(prot);
ring R=32003,(d2,d1,d0,dm1,{','.join(allv)},z,t),dp;
poly D2={window(AV)};
poly D1={window(BV)};
poly D0={window(CV)};
poly E ={window(EV)};
poly U =-(2048*(t-1)^4-512*(t-1)^3+320*(t-1)^2-240*(t-1)+195)/6630;
poly H0={hs[0]};
H0=subst(H0,d2,D2,d1,D1,d0,D0,dm1,E);
poly H1={hs[1]};
H1=subst(H1,d2,D2,d1,D1,d0,D0,dm1,E);
int i;
// block 1: coeffs t^0..t^29 of H0
matrix C0=coeffs(H0,t);
"t-degree+1 of H0 (expect <=41):",nrows(C0);
ideal B1;
for(i=1;i<=30;i++){{ B1[i]=C0[i,1]; }}

// g1 = H0/t^30 assembled from the high coefficients (rows 31..)
poly G1=0;
for(i=31;i<=nrows(C0);i++){{ G1=G1+C0[i,1]*t^(i-31); }}
poly N2=E^3*G1+U*H1;
matrix C2=coeffs(N2,t);
ideal B2;
for(i=1;i<=30;i++){{ B2[i]=C2[i,1]; }}

ideal Iaux=z*e0-1;                   // a=0 stratum: e0 != 0

"=== BLOCK 1 (30 eqs, deg 10) + e0!=0 ===";
ideal J1=B1,Iaux;
ideal S1=std(J1);
"block1 GB size:",size(S1),"  dim (true = this - 5):",dim(S1);

"=== BLOCKS 1+2 (60 eqs) + e0!=0 ===";
ideal J2=B1,B2,Iaux;
ideal S2=std(J2);
"block1+2 GB size:",size(S2),"  dim (true = this - 5):",dim(S2);
if(S2[1]==1){{ "*** INCONSISTENT: branch (i) blocks 1+2 empty over F_p ***"; }}
quit;
"""

open('t5_cascade.sing', 'w').write(sc)
print("wrote t5_cascade.sing")
