"""
t5_msolve_export.py — COPY of t5_block1_dehom_gen.py modified to export the
ideal generators of Q1/Q2/Q3 (see t5_block1_dehom_gen.py for the math) to
plain text files (one polynomial per line, short=0 so '*' and '^' explicit),
for conversion to msolve input format by singular_to_msolve.py.

Writes t5_msolve_export.sing; running it in Singular produces
  q1_gens.txt  (block1, 30 eqs)
  q2_gens.txt  (A0, 41 eqs)
  q3_gens.txt  (A0 + BB1, 71 eqs)
No Groebner computation is performed here — only substitution/coeffs.
"""
import re

hs = {}
for m in re.finditer(r'h_(\d) \(weight \d+, dm1-power \d+\) = (.+)',
                     open('f31_graded.txt').read()):
    hs[int(m.group(1))] = m.group(2).replace('**', '^')

AV = [f'a{i}' for i in range(5)]
BV = [f'b{i}' for i in range(7)]
CV = [f'c{i}' for i in range(9)]
EV = [f'e{i}' for i in range(1, 11)]          # e0 = 1 substituted out
allv = AV + BV + CV + EV

sc = f"""// generated by t5_msolve_export.py — do not edit by hand
short=0;
ring R=32003,(d2,d1,d0,dm1,{','.join(allv)},t),dp;
short=0;
poly D2={'+'.join(f'a{i}*t^{i}' if i else 'a0' for i in range(5))};
poly D1={'+'.join(f'b{i}*t^{i}' if i else 'b0' for i in range(7))};
poly D0={'+'.join(f'c{i}*t^{i}' if i else 'c0' for i in range(9))};
poly E =1+{'+'.join(f'e{i}*t^{i}' for i in range(1, 11))};
poly H0={hs[0]};
H0=subst(H0,d2,D2,d1,D1,d0,D0,dm1,E);
poly H1={hs[1]};
H1=subst(H1,d2,D2,d1,D1,d0,D0,dm1,E);

int i;
matrix C0=coeffs(H0,t);
matrix C1=coeffs(H1,t);
"nrows C0,C1 (expect 41,37):",nrows(C0),nrows(C1);

ideal B1; for(i=1;i<=30;i++){{ B1[i]=C0[i,1]; }}
ideal A0; for(i=1;i<=nrows(C0);i++){{ A0[i]=C0[i,1]; }}
ideal BB1; for(i=1;i<=30;i++){{ BB1[i]=C1[i,1]; }}
ideal Q3=A0,BB1;

write(":w q1_gens.txt","");
for(i=1;i<=ncols(B1);i++){{ write(":a q1_gens.txt",string(B1[i])); }}
write(":w q2_gens.txt","");
for(i=1;i<=ncols(A0);i++){{ write(":a q2_gens.txt",string(A0[i])); }}
write(":w q3_gens.txt","");
for(i=1;i<=ncols(Q3);i++){{ write(":a q3_gens.txt",string(Q3[i])); }}
"wrote q1_gens.txt / q2_gens.txt / q3_gens.txt";
quit;
"""

open('t5_msolve_export.sing', 'w').write(sc)
print("wrote t5_msolve_export.sing")
