"""
t5_pivot_gen.py — per-base exact certificate attempt for T5 branch (i)
(a=0 stratum, f31 subcase-2), via the pivoted incremental t-adic lift.

Strategy (see T5_NP.md): fix a random F_p base point p0=(a0,b0,c0,e0) on
h31=0 with e0 != 0, grad_{d0} != 0, grad_{dm1} != 0. The t-slices 1..10 of
h31(d~)=0 mod t^30 then determine pivots c_1..c_8, e_9, e_10 as POLYNOMIALS
in the 18 free window coefficients (a1..a4, b1..b6, e1..e8) — the pivot
denominators are the constant gradient entries. The remaining conditions are:
  * slices 11..29 of h31(d~)               (19 consistency eqs)
  * cascade blocks 2..7 and the terminal   (up to 221 more)
all polynomials in the 18 frees over F_p. Feed them incrementally to slimgb;
1 in the ideal at any stage = NO window solution over F_p-bar with this base
= an exact per-base certificate (vs the numeric positive floor).

All arithmetic happens inside qring S/(t^41) so products auto-truncate.

This generator picks the base in sympy (GF(p)), then emits t5_pivot.sing.
"""
import re, random, sympy as sp

P = 32003
rng = random.Random(20260721)

# ---- load h_f --------------------------------------------------------------
hs_src = {}
for m in re.finditer(r'h_(\d) \(weight \d+, dm1-power \d+\) = (.+)',
                     open('f31_graded.txt').read()):
    hs_src[int(m.group(1))] = m.group(2)

d2, d1, d0, dm1 = sp.symbols('d2 d1 d0 dm1')
h0 = sp.sympify(hs_src[0])

# ---- find base on h31=0 with e0!=0 and usable gradient ---------------------
g_d0 = sp.diff(h0, d0)
g_dm1 = sp.diff(h0, dm1)
base = None
while base is None:
    a0, b0, c0 = (rng.randrange(1, P) for _ in range(3))
    poly = sp.Poly(h0.subs({d2: a0, d1: b0, d0: c0}), dm1, modulus=P)
    for r, _ in sp.ground_roots(poly).items():
        e0 = int(r) % P
        if e0 == 0:
            continue
        sub = {d2: a0, d1: b0, d0: c0, dm1: e0}
        gd0 = int(g_d0.subs(sub)) % P
        gdm = int(g_dm1.subs(sub)) % P
        if gd0 and gdm:
            base = (a0, b0, c0, e0, gd0, gdm)
            break
a0, b0, c0, e0, gd0, gdm = base
chk = int(h0.subs({d2: a0, d1: b0, d0: c0, dm1: e0})) % P
assert chk == 0
print(f"base p0 = (a0,b0,c0,e0) = ({a0},{b0},{c0},{e0}) over F_{P}")
print(f"grad_d0 = {gd0}, grad_dm1 = {gdm}  (both nonzero)")

inv_gd0 = pow(gd0, P - 2, P)
inv_gdm = pow(gdm, P - 2, P)

FREES = ([f'a{i}' for i in range(1, 5)] + [f'b{i}' for i in range(1, 7)]
         + [f'e{i}' for i in range(1, 9)])

hpolys = "\n".join(
    f"poly h{f}={hs_src[f].replace('**','^')};" for f in range(8))

sc = f"""// generated by t5_pivot_gen.py — do not edit by hand
// base ({a0},{b0},{c0},{e0}); pivots c1..c8 (inv grad {inv_gd0}), e9,e10 (inv grad {inv_gdm})
option(prot);
ring S0=32003,(d2,d1,d0,dm1,{','.join(FREES)},t),dp;
ideal TQ=t^41;
qring S=std(TQ);
{hpolys}
poly U=-(2048*(t-1)^4-512*(t-1)^3+320*(t-1)^2-240*(t-1)+195)/6630;

// windows: known parts; pivots appended as they are computed
poly D2={a0}+{'+'.join(f'a{i}*t^{i}' for i in range(1,5))};
poly D1={b0}+{'+'.join(f'b{i}*t^{i}' for i in range(1,7))};
poly D0={c0};
poly E ={e0}+{'+'.join(f'e{i}*t^{i}' for i in range(1,9))};

proc tslice(poly F, int j) {{
  // coefficient of t^j in F (a poly in the frees)
  matrix M=coeffs(F,t);
  if (nrows(M) < j+1) {{ return(poly(0)); }}
  return(M[j+1,1]);
}}

int j;
poly H, K, piv;
// ---- pivot lift: slices 1..10 of h31(D~) ----
for (j=1; j<=10; j++) {{
  H=subst(subst(subst(subst(h0,d2,D2),d1,D1),d0,D0),dm1,E);
  K=tslice(H,j);
  if (j<=8) {{ piv=-K*{inv_gd0}; D0=D0+piv*t^j; }}
  else      {{ piv=-K*{inv_gdm}; E =E +piv*t^j; }}
  "pivot slice",j,"done; pivot terms:",size(piv);
}}

// ---- full h31 series; consistency slices 11..29; g1 from slices 30..40 ----
H=subst(subst(subst(subst(h0,d2,D2),d1,D1),d0,D0),dm1,E);
"sanity: slices 0..10 all zero:";
for (j=0; j<=10; j++) {{ if (tslice(H,j)!=0) {{ "SLICE",j,"NONZERO — BUG"; }} }}
ideal CONS;
int nc=0;
for (j=11; j<=29; j++) {{ nc++; CONS[nc]=tslice(H,j); }}
"block-1 consistency eqs:",nc;

poly G1=0;
for (j=30; j<=40; j++) {{ G1=G1+tslice(H,j)*t^(j-30); }}

// ---- block 2: t-slices 0..29 of E^3*G1 + U*h1(D~) ----
poly H1=subst(subst(subst(subst(h1,d2,D2),d1,D1),d0,D0),dm1,E);
poly N=E^3*G1+U*H1;
for (j=0; j<=29; j++) {{ nc++; CONS[nc]=tslice(N,j); }}
"after block 2:",nc,"eqs";

// ---- incremental groebner: block1 cons, then +block2 ----
ideal C1;
for (j=1; j<=19; j++) {{ C1[j]=CONS[j]; }}
"=== slimgb on 19 block-1 consistency eqs (18 frees) ===";
ideal SG1=slimgb(C1);
"GB size:",size(SG1),"  dim:",dim(SG1);
if (SG1[1]==1) {{ "*** INCONSISTENT at block 1 — per-base certificate ***"; }}

"=== slimgb on blocks 1+2 (49 eqs) ===";
ideal SG2=slimgb(CONS);
"GB size:",size(SG2),"  dim:",dim(SG2);
if (SG2[1]==1) {{ "*** INCONSISTENT at block 2 — PER-BASE CERTIFICATE ACHIEVED ***"; }}
else {{ "still consistent after blocks 1+2; add blocks 3+ next"; }}
quit;
"""

open('t5_pivot.sing', 'w').write(sc)
print("wrote t5_pivot.sing")
