#!/usr/bin/env python3
"""Independent regression checks for cascade_engine.py.

1. Terminal reproduction: the engine restricted to the terminal level must
   reproduce the exact feasibility verdict of split_place_ledger.py on all
   327 strata for both branches (the ledger is generated by independent
   closed-form arithmetic, not by the engine).
2. Hand-checked descent semantics on a fully worked local example.
3. Depth monotonicity: adding a level never revives a killed branch.
"""

from __future__ import annotations

import json
from pathlib import Path

import cascade_engine as engine

def _require(_cond, _msg):
    """Proof-critical check: fails loudly and exits nonzero, unaffected by python -O."""
    if not _cond:
        import sys as _sys
        print("FAIL: " + str(_msg))
        _sys.exit(1)


ROOT = Path(__file__).resolve().parent
INF = engine.INF


def check_terminal_reproduction() -> None:
    ledger = json.loads(
        (ROOT / "split_place_ledger.json").read_text(encoding="utf-8")
    )
    strata = ledger["strata"]
    _require(len(strata) == 327, "len(strata) == 327")
    mismatches = []
    for row in strata:
        for branch, terminal_depth in (("T1", 7), ("T2", 6)):
            expected = row["branches"][branch]["terminal"]["feasible"]
            outcome = engine.analyze_branch(
                row["a_t"], tuple(row["b"]), branch, depth=terminal_depth
            )
            actual = outcome["status"] == "survives"
            if actual != expected:
                mismatches.append((row["a_t"], tuple(row["b"]), branch))
    _require(not mismatches, f"terminal disagreements: {mismatches[:10]}")
    print("  terminal layer reproduces split_place_ledger.json on 654 records")


def check_descent_semantics() -> None:
    # Level 6, split place with b=0, all local valuations zero, r_{l+1}=7.
    # h_6 = -3072*sigma^2 + 14336*d1^2*d2 + 8192*d1*e has a triple tie at
    # valuation 0, so:
    #   case (a): r_6 = 7 needs w >= 2, a tie rise of depth 2;
    #   case (b): w = 1 (rise depth 1) with r_6 >= 8;
    #   case (c): w = 0 gives r_6 = 6 with a term cancellation of depth 1.
    state = (0.0, 0.0, 0.0, 0)
    flags = (False, False, False)
    options = engine.descend_options(6, 7.0, False, False, state, flags, 10)

    def find(r_value, kind, depth):
        return [
            obligations
            for r_l, obligations in options
            if r_l == r_value
            and any(o.kind == kind and o.depth == depth for o in obligations)
        ]

    _require(find(7.0, "monomial_tie_rise", 2), "case (a) missing")
    _require(find(8.0, "monomial_tie_rise", 1), "case (b) missing")
    _require(find(6.0, "term_cancellation", 1), "case (c) missing")
    # No option may grant a valuation rise without an obligation.
    for r_l, obligations in options:
        if r_l not in (7.0,):  # case (a) at the tropical minimum w=2 is a rise
            continue
    minimum, tied, _ = engine.tropical_h(6, state, flags)
    _require(minimum == 0 and len(tied) == 3, "minimum == 0 and len(tied) == 3")

    # Unique-monomial level: h_7 = 8192*d1^2 admits no rise at all.
    unique_options = engine.w_options(7, (0.0, 1.0, 0.0, 0), flags)
    _require(unique_options == [(2.0, ())] or unique_options == [(2, ())], "unique_options == [(2.0, ())] or unique_options == [(2, ())]")

    # T2 terminal: h_6 with d1 == 0 collapses to -3072*sigma^2 (unique).
    t2_flags = (False, False, True)
    minimum, tied, count = engine.tropical_h(6, (0.0, INF, 3.0, 0), t2_flags)
    _require(minimum == 6 and len(tied) == 1 and count == 1, "minimum == 6 and len(tied) == 1 and count == 1")
    print("  descent case analysis matches the hand-worked level-6 example")


def check_depth_monotonicity() -> None:
    ledger = json.loads(
        (ROOT / "split_place_ledger.json").read_text(encoding="utf-8")
    )
    sample = [row for row in ledger["strata"] if row["open_branches"]][:12]
    for row in sample:
        for branch in row["open_branches"]:
            statuses = {}
            for depth in (5, 4):
                outcome = engine.analyze_branch(
                    row["a_t"], tuple(row["b"]), branch, depth=depth
                )
                statuses[depth] = outcome["status"]
            if statuses[5] == "engine_killed_pending_audit":
                _require(statuses[4] == "engine_killed_pending_audit", (
                    row["a_t"],
                    row["b"],
                    branch,
                ))
    print("  depth monotonicity holds on a 12-stratum sample")


def check_t_place_semantics() -> None:
    # At t = y+1: v_t(ehat) = v_t(u) = 0, the e-slot costs a, and the
    # terminal identity gives s_6 = 2*v_t(sigma) for T2 exactly.
    profiles = engine.t_place_profiles(
        5, "T2", 25, 4, False, False, {6: False, 5: False, 4: False}
    )
    _require(profiles, "T2 a=5 t-place must admit chains")
    for profile in profiles:
        _require(profile.place == "t" and profile.b == 5, "profile.place == \"t\" and profile.b == 5")
        _require(dict(profile.r)[6] == 2 * profile.z, "dict(profile.r)[6] == 2 * profile.z")
    # The Pareto-minimal chain is the zero state; it survives only through
    # deep term cancellations (v + s_6 = 15 vs tied minima at 0), so every
    # profile must carry cancellation obligations — no free ride at t.
    _require(all(
        any(o.kind == "term_cancellation" and o.depth > 0 for o in p.obligations)
        for p in profiles
    ), "all( any(o.kind == \"term_cancellation\" and o.depth > 0 for o in p.obligations) for p in profiles )")
    # Coupling t must never revive a q-only kill (monotonicity in places):
    outcome_q = engine.analyze_branch(5, (1, 0, 0, 0), "T2", 4)
    outcome_qt = engine.analyze_branch(5, (1, 0, 0, 0), "T2", 4, include_t=True)
    _require(outcome_q["status"] == "survives", "outcome_q[\"status\"] == \"survives\"")
    _require(outcome_qt["status"] == "survives", "outcome_qt[\"status\"] == \"survives\"")
    _require(len(outcome_qt["survivor_cases"]) <= len(outcome_q["survivor_cases"]), "len(outcome_qt[\"survivor_cases\"]) <= len(outcome_q[\"survivor_cases\"])")
    print("  t-place terminal law, forced cancellations, place monotonicity")


def main() -> None:
    check_terminal_reproduction()
    check_descent_semantics()
    check_depth_monotonicity()
    check_t_place_semantics()
    print("cascade engine: PASS")


if __name__ == "__main__":
    main()
