#!/usr/bin/env python3
"""Clean-clone guard (FIRST line of the test suite).

A fresh public clone must be able to run the whole test suite.  That fails
silently if any suite checker reads a file that is NOT tracked in git (a
git-ignored artifact, a locally-present-but-uncommitted input, etc.): the file
is there on the author's machine but vanishes on a clean clone.

This tool runs every checker named in run_tests.sh under a Python audit hook
that records each real file the checker OPENS FOR READING beneath the repo, then
asserts every such file is tracked by ``git ls-files``.  Any opened-but-untracked
file fails the whole suite loudly, here, before anything else runs.

Files only touched behind an ``is_file()``/``exists()`` guard (optional
provenance paths against a local pickle or .tex) are naturally covered: if the
guard is false the file is never opened, so it is never required; if it IS opened
it must be tracked.

Exit 0 iff every opened repo file is git-tracked.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
import time
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
REPO = TOOLS.parent


def norm(p: str) -> str:
    return os.path.normcase(os.path.realpath(p))


def tracked_files() -> set[str]:
    out = subprocess.run(
        ["git", "-C", str(REPO), "ls-files"],
        capture_output=True, text=True, check=True,
    ).stdout.splitlines()
    return {norm(str(REPO / line)) for line in out if line.strip()}


# Match the two suite-driving patterns in run_tests.sh:
#   ( cd "$here/<dir>" && ...
#   python3 <script>.py [args...]
_CD = re.compile(r'cd\s+"\$here/([^"]+)"')
_PY = re.compile(r'python3\s+([A-Za-z0-9_./]+\.py)([^\n&|]*)')


def suite_commands(run_tests: Path) -> list[tuple[str, str, list[str]]]:
    """Parse run_tests.sh -> [(subdir, script, args)] in order.

    Skips the slow positive control (jetlift.py control ...): it is gated by
    SKIP_SLOW in the suite and reads only tracked inputs, and running it here
    would double a multi-minute step.  The clean-clone risk lives in the exact
    checkers, all of which are covered."""
    text = run_tests.read_text(encoding="utf-8")
    cmds: list[tuple[str, str, list[str]]] = []
    cur = "."
    for line in text.splitlines():
        m = _CD.search(line)
        if m:
            cur = m.group(1)
        for pm in _PY.finditer(line):
            script = pm.group(1)
            args = pm.group(2).split()
            if script.endswith("jetlift.py") and "control" in args:
                continue
            # skip self-reference
            if script.endswith("clean_clone_check.py"):
                continue
            cmds.append((cur, script, args))
    return cmds


_TRACER = r'''
import os, runpy, sys
_OUT = os.environ["CLEAN_CLONE_OUT"]
_REPO = os.path.normcase(os.path.realpath(os.environ["CLEAN_CLONE_REPO"]))
# Append each newly-seen opened file IMMEDIATELY (line-buffered) so captures
# survive even if this process is killed by the driver's timeout after the
# input-reading phase (checkers read their data up front, then compute).
_seen = set()
_fh = open(_OUT, "w", encoding="utf-8", buffering=1)

def _is_write(mode, flags):
    if isinstance(mode, str) and any(c in mode for c in "wax+"):
        return True
    if isinstance(flags, int) and flags >= 0:
        wr = os.O_WRONLY | os.O_RDWR | getattr(os, "O_CREAT", 0)
        if flags & wr:
            return True
    return False

def _hook(event, args):
    if event != "open":
        return
    path, mode, flags = (list(args) + [None, None, None])[:3]
    if not isinstance(path, (str, bytes, os.PathLike)):
        return
    try:
        real = os.path.normcase(os.path.realpath(os.fspath(path)))
    except (TypeError, ValueError):
        return
    if not real.startswith(_REPO + os.sep) or real in _seen:
        return
    # Ignore generated bytecode / VCS internals: never source, always regenerated
    # on a clean clone, and correctly git-ignored.
    if "__pycache__" in real or real.endswith(".pyc") or (os.sep + ".git" + os.sep) in real:
        return
    if _is_write(mode, flags):
        return
    if os.path.isfile(real):
        _seen.add(real)
        try:
            _fh.write(real + "\n"); _fh.flush()
        except (ValueError, OSError):
            pass

sys.addaudithook(_hook)

_script = os.environ["CLEAN_CLONE_SCRIPT"]
sys.argv = [_script] + os.environ.get("CLEAN_CLONE_ARGS", "").split()
try:
    runpy.run_path(_script, run_name="__main__")
except SystemExit:
    pass
'''

# We only need each checker's file OPENS, which happen up front.  So we stop a
# checker once it has gone QUIET_S seconds without opening a new repo file
# (quiescence) -- or when it exits naturally, or at a hard cap.  This keeps the
# guard fast even though some checkers compute for minutes after loading.
QUIET_S = 8.0       # stop this long after the last new open
HARD_CAP_S = 90.0   # absolute per-checker ceiling
POLL_S = 0.25


def run_one(subdir: str, script: str, args: list[str]) -> set[str]:
    workdir = (REPO / subdir).resolve()
    script_path = (workdir / script)
    with tempfile.NamedTemporaryFile("r", suffix=".txt", delete=False) as tf:
        out_path = tf.name
    env = dict(os.environ)
    env["CLEAN_CLONE_OUT"] = out_path
    env["CLEAN_CLONE_REPO"] = str(REPO)
    env["CLEAN_CLONE_SCRIPT"] = str(script_path)
    env["CLEAN_CLONE_ARGS"] = " ".join(args)
    proc = subprocess.Popen(
        [sys.executable, "-c", _TRACER],
        cwd=str(workdir), env=env,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    start = time.monotonic()
    last_size = -1
    last_change = start
    while True:
        if proc.poll() is not None:
            break  # exited naturally
        now = time.monotonic()
        try:
            size = os.path.getsize(out_path)
        except OSError:
            size = last_size
        if size != last_size:
            last_size = size
            last_change = now
        # Stop once opens have been quiet for QUIET_S (past a short warmup), or
        # at the hard ceiling.  Reads are flushed on open, so captures persist.
        if (now - last_change > QUIET_S and now - start > 2.0) or (now - start > HARD_CAP_S):
            proc.terminate()
            try:
                proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                proc.kill()
            break
        time.sleep(POLL_S)
    try:
        opened = {norm(p) for p in Path(out_path).read_text(encoding="utf-8").splitlines() if p.strip()}
    finally:
        os.unlink(out_path)
    return opened


def main() -> int:
    run_tests = REPO / "run_tests.sh"
    if not run_tests.is_file():
        print(f"[clean_clone_check] FAIL: {run_tests} not found", file=sys.stderr)
        return 1

    tracked = tracked_files()

    # The two originals that de-risk the clean clone must themselves be tracked.
    must_track = []
    for rel in ("generators.json", "paper_src/upstream_facts.json"):
        for base in ("d2_plane_72_108", "d2"):
            cand = REPO / base / rel
            if cand.is_file():
                must_track.append(cand)
    hard_fail = []
    for f in must_track:
        if norm(str(f)) not in tracked:
            hard_fail.append(f"{f} exists but is NOT git-tracked")

    cmds = suite_commands(run_tests)
    all_opened: set[str] = set()
    print(f"[clean_clone_check] tracing {len(cmds)} suite checkers for file opens ...", flush=True)
    for i, (subdir, script, args) in enumerate(cmds, 1):
        opened = run_one(subdir, script, args)
        all_opened |= opened
        print(f"  [{i:2d}/{len(cmds)}] {subdir}/{script}: {len(opened)} repo files", flush=True)

    untracked = sorted(p for p in all_opened if p not in tracked)

    # Present relative paths for readability.
    def rel(p: str) -> str:
        try:
            return os.path.relpath(p, str(REPO))
        except ValueError:
            return p

    print(f"[clean_clone_check] {len(all_opened)} distinct repo files opened for reading.")
    if hard_fail or untracked:
        print("\n[clean_clone_check] FAIL — a clean clone would be missing files the suite reads:",
              file=sys.stderr)
        for msg in hard_fail:
            print(f"  * {msg}", file=sys.stderr)
        for p in untracked:
            print(f"  * OPENED BUT UNTRACKED: {rel(p)}", file=sys.stderr)
        return 1

    print("[clean_clone_check] OK — every file opened by the suite is tracked in git.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
